### ISSUE TITLE
Questions 

### ISSUE THREAD

**Issue by luciewho** [Shoalsteed/UX#15]
Questions that I had while installing and getting familiar with I2P

**Comment by luciewho** [comment]
I'm learning that I2P doesn’t have something called outproxies, can’t access clearweb (regular internet), you can only use internal services. 

Seems like for a researcher or developer, they would use I2P to experiment and build new services or apps, create websites, torrenting (I'm familiar with torrenting movies or other media, is this the same on I2P?). Anything else?

How would someone non-technical like a journalist use I2P? Would they use it for email and file sharing mostly? Would they be emailing or sharing with their sources/other journalists who are also on I2P? I'm wondering if there are specific case studies or examples that describe how non-technical people use I2P.

I think having an understanding of this will help build out a Getting Started guide and the use cases and workflows.

**Comment by Shoalsteed** [comment]
The I2P network allows you to do most things that you can do on the internet.

For any casual user ( like me) I can use the apps that ship with the software to torrent content, or I can use email, or use the static webpage to build my own small site.
For devs, the sky is the limit- make apps, SSH, create more robust sites, host forums, and more. 

What is missing from the Product is this story - clearly showing what the software allows a person using it to do. 

For journalists, yes, using nyms and keeping their traffic / activities confined to the i2P network would be the best for risk management. They could use email, torrents, and even host private non-discoverable sites if they wanted.

**Comment by Shoalsteed** [comment]
here https://github.com/Shoalsteed/UX/issues/11 are some user stories that I  started to try to write

**Comment by luciewho** [comment]
Is there any past research on interviews with users? Transcripts or audio from the interviews?

**Comment by luciewho** [comment]
How much of what's already on the website can be removed? Is everything essential?

**Comment by luciewho** [comment]
An example I'm thinking of is this. Can this be removed or consolidated within the installation guide? 

<img width="778" alt="Screen Shot 2021-07-28 at 2 39 16 PM" src="https://user-images.githubusercontent.com/6728799/127399829-c0b1e912-a2df-4778-9e3b-4d3b22f71b01.png">

**Comment by Shoalsteed** [comment]
> Is there any past research on interviews with users? Transcripts or audio from the interviews?

not that I am aware of at all.

**Comment by Shoalsteed** [comment]
> An example I'm thinking of is this. Can this be removed or consolidated within the installation guide?
> 
> <img alt="Screen Shot 2021-07-28 at 2 39 16 PM" width="778" src="https://user-images.githubusercontent.com/6728799/127399829-c0b1e912-a2df-4778-9e3b-4d3b22f71b01.png">

![post install](https://user-images.githubusercontent.com/50714166/127401636-2413fc42-e2a3-451e-8d79-b3787aebdaf2.png)

Here is the direction for Post install

**Comment by Shoalsteed** [comment]
so, keeping it to download and install and then providing links to setting up browser, or more advanced config options. So, thinning out that info is fine and in the plans!

**Comment by luciewho** [comment]
How much of the changes we propose will be implemented? Who makes the final decision? Is there somebody that has to approve the proposed changes?

**Comment by Shoalsteed** [comment]
Myself and IDK
