### ISSUE TITLE
Getting Started: the I2P Product Guide For New Users

### ISSUE THREAD

**Issue by Shoalsteed** [Shoalsteed/UX#17]

**Comment by luciewho** [comment]
I realized that the "Getting Started" phrase is already used on the download page. There should probably be some distinction in the phrasing. Could remove "getting started" on the download page and call it Installation or Download.

<img width="757" alt="Screen Shot 2021-07-28 at 10 39 52 AM" src="https://user-images.githubusercontent.com/6728799/127371445-28ad6e5e-7a4d-43e4-9282-320ea0f17657.png">

Installation or Download > Post-Installation or Setting Up guide > Getting Started 

Installation or Download = you need to download the file, download java 
Post-Install  = you need to configure the browser and use Sadie's guide to walk through the wizard
Getting Started = you are able to launch I2P on your browser, you want to know what you can do with I2P

Maybe there also is a better phrase besides "Getting Started" ?
Download > Installation > Getting Started is another idea

**Comment by Shoalsteed** [comment]
This should include:
Guides for installing I2P on Windows and Mac
Configuring your browser
An introduction to the console ie - sidebar, where to finding things
Proper introductions to the applications and configurations within the console
include links to places to get support or good examples of use cases ie good sites, neat things you can do.
FAQ 
Troubleshooting 
A what the software is / why use it product pitch.

**Comment by Shoalsteed** [comment]
> I realized that the "Getting Started" phrase is already used on the download page. There should probably be some distinction in the phrasing. Could remove "getting started" on the download page and call it Installation or Download.
> 
> <img alt="Screen Shot 2021-07-28 at 10 39 52 AM" width="757" src="https://user-images.githubusercontent.com/6728799/127371445-28ad6e5e-7a4d-43e4-9282-320ea0f17657.png">
> 
> Installation or Download > Post-Installation or Setting Up guide > Getting Started
> 
> Installation or Download = you need to download the file, download java
> Post-Install = you need to configure the browser and use Sadie's guide to walk through the wizard
> Getting Started = you are able to launch I2P on your browser, you want to know what you can do with I2P
> 
> Maybe there also is a better phrase besides "Getting Started" ?
> Download > Installation > Getting Started is another idea

I removed the "Getting Started" in the updated text for the download page!

**Comment by luciewho** [comment]
Are you thinking Getting Started would be a page that replaces Post-Install?

**Comment by Shoalsteed** [comment]
The Post Install should be just a 'hey great, your download is happening" and then links to a Getting Started Guide I think since it only appears after the download starts. That way also the information required for Getting Started is better accessible. I think that it would be added to the top menu or replace About.

**Comment by luciewho** [comment]
Got it, that makes sense. So the ideal flow would be something like: Download > Post-Install > Getting Started 

Installation or Download = you need to download the file, download java
Post-Install = your download is happening. click here to get started.
Getting Started = everything you mentioned above (guide, configuring browser, FAQ, use cases, intro, troubleshooting, etc)

As I'm thinking through this...I suggest that the guide you made on Medium be associated with Post-Install, because I consider it to be part of the installation process. There could be a link to the guide on the Post-Install page but it should be separate from the Getting Started page. That way, it also cuts down the amount of content/info for Getting Started, because I could see it become overwhelming. 

Hope that makes sense. I could put together some high level wireframes / flows for what this could look like and we can pick out what works best.

**Comment by Shoalsteed** [comment]
what I was thinking was having a link on the download page in the Mac section for that guide, similar to how the Windows one is set up. Have a look at Mullvad for my inspiration https://mullvad.net/en/

**Comment by Shoalsteed** [comment]
> Got it, that makes sense. So the ideal flow would be something like: Download > Post-Install > Getting Started
> 
> Installation or Download = you need to download the file, download java
> Post-Install = your download is happening. click here to get started.
> Getting Started = everything you mentioned above (guide, configuring browser, FAQ, use cases, intro, troubleshooting, etc)
> 
> As I'm thinking through this...I suggest that the guide you made on Medium be associated with Post-Install, because I consider it to be part of the installation process. There could be a link to the guide on the Post-Install page but it should be separate from the Getting Started page. That way, it also cuts down the amount of content/info for Getting Started, because I could see it become overwhelming.
> 
> Hope that makes sense. I could put together some high level wireframes / flows for what this could look like and we can pick out what works best.

yes, if you would like to create some wireframes , that would be wonderful!

**Comment by luciewho** [comment]
I like how the menu is organized and this Getting Started page: https://aws.amazon.com/ec2/getting-started/

Download/Configure is part of Getting Started and each step is broken down into its own "card."

I like that the Resources includes Developer Resources for more technical information

![Screen Shot 2021-07-29 at 4 07 38 PM](https://user-images.githubusercontent.com/6728799/127576754-74f6c658-f13f-49bc-b4cc-93faaf97d2c5.png)

**Comment by Shoalsteed** [comment]
this is a good information layout for sure.

Having one menu page that leads to a page like this would reduce that huge sprawling menu too.

**Comment by luciewho** [comment]
Wireframe for Getting Started page based on the AWS page above (I tried with the copy but it's sparse and not good lol). Should we create a getting started page? 

[Getting Started.pdf](https://github.com/Shoalsteed/UX/files/6910385/Getting.Started.pdf)

**Comment by Shoalsteed** [comment]
For the Install section: 
Follow the step-by-step guide to install here
based on your operating system.
You will be taken through a wizard walk
through.

**"Step-by-step installation guides based on your operation system can be found here: link These include setting up java, installing I2P and using the I2P set up wizard to check your bandwidth settings, which is optional"**

**Comment by Shoalsteed** [comment]
![1](https://user-images.githubusercontent.com/50714166/128764901-880a1062-1075-45c4-999b-03f72cd6fc86.png)
![2](https://user-images.githubusercontent.com/50714166/128764904-b53f8a51-7250-45cf-9121-b8fba2b114be.png)

I posted these in the FAQ issue , but they should be here as well.

**Comment by Shoalsteed** [comment]
what is missing: 
set up a site or forum
create a router troubleshooting section 
maybe remove new devs guide and include that in the dev onboarding instead

**Comment by Shoalsteed** [comment]
https://jami.biz/jams-user-guide - here is the Jami admin guide for their enterprise software. I think that this might make sense for I2P as well. 

"Discover I2P For Developers" might be the best way to go

**Comment by luciewho** [comment]
> https://jami.biz/jams-user-guide - here is the Jami admin guide for their enterprise software. I think that this might make sense for I2P as well.
> 
> "Discover I2P For Developers" might be the best way to go

This is great! Good inspiration

**Comment by luciewho** [comment]
I mentioned that the Getting Started page should look different from those Step 1-2-3 cards that will be on the download page now. This is what I'm thinking it could look like? Not sure about this, might need to keep working on it.

[Getting Started v3.pdf](https://github.com/Shoalsteed/UX/files/6997381/Getting.Started.v3.pdf)

**Comment by Shoalsteed** [comment]
<img width="818" alt="Screen Shot 2021-08-17 at 11 32 37 AM" src="https://user-images.githubusercontent.com/50714166/129755945-c24f0765-398d-40dd-82d8-ec6ed617e768.png">

I am wondering how to change this to direct people to the software guide as well?
This is really good !

**Comment by luciewho** [comment]
Yeah, that would be good to add! I'll make a note of that
