### ISSUE TITLE
About pages

### ISSUE THREAD

**Issue by luciewho** [Shoalsteed/UX#19]
Notes on the pages within the About section

**Comment by luciewho** [comment]
**Introduction to I2P**

Lots of text. I can kind of understand the first three paragraphs (What is I2P?, I2P Cares About Privacy, How to Connect) though there is still some abstract concepts I'm not entirely familiar with as a non-developer like "network layer", "encrypted unidirectional tunnels", "pattern recognition", "DNS", "self host or mirror content." The paragraphs below (An Overview of the Network, About Decentralization and I2P) are where I start to feel lost, the jargon increases. 

It's good that the paragraphs are short, rather than a wall of text. It would be nice to break up some of the text by having visual elements. 

https://2019.www.torproject.org/about/overview.html.en
I noticed that Tor has a video, which is engaging and easy to understand. The text below it is also a lot. There are some images that describe how Tor works, but I'm not sure how helpful they are. It is still difficult for a non-developer like me to understand, I have really focus on what I'm reading in order to understand what's going on.

**Comment by luciewho** [comment]
**What is Included** 

The text on this page doesn't feel jargon-y. I read through everything quite easily. 

I2PSnark and The Address Book link to other pages. Those pages could be improved. For example, I2PSnark links to a page about trackers? The text doesn't seem relevant to I2PSnark, and I2PSnark is not mentioned once on there. 

The links could be more obvious. The color, a dark gray, blends in with regular non-clickable text which is black. 

Maybe screenshots or visuals to go along with each application? Might look messy on this page, however.

**Comment by luciewho** [comment]
**How to Browse I2P** 

This page is very similar to the post-install page. The Post-Install Work section is not there, but there is the Firefox Profile for Windows and How to configure your browser sections.

Will a user that has either already downloaded or not yet downloaded I2P need to access this page? I can see how someone that downloads but didn't complete installation would want to refer to the installation guide and know how to configure their browser. This page might not be useful for someone trying to learn about I2P.

**Comment by Shoalsteed** [comment]
> **Introduction to I2P**
> 
> Lots of text. I can kind of understand the first three paragraphs (What is I2P?, I2P Cares About Privacy, How to Connect) though there is still some abstract concepts I'm not entirely familiar with as a non-developer like "network layer", "encrypted unidirectional tunnels", "pattern recognition", "DNS", "self host or mirror content." The paragraphs below (An Overview of the Network, About Decentralization and I2P) are where I start to feel lost, the jargon increases.
> 
> It's good that the paragraphs are short, rather than a wall of text. It would be nice to break up some of the text by having visual elements.
> 
> https://2019.www.torproject.org/about/overview.html.en
> I noticed that Tor has a video, which is engaging and easy to understand. The text below it is also a lot. There are some images that describe how Tor works, but I'm not sure how helpful they are. It is still difficult for a non-developer like me to understand, I have really focus on what I'm reading in order to understand what's going on.

This is where I wonder how important it is to actually include any of how it works to new users. It should maybe stick to what it does with a very high level graphic and explanation for how it works. 

For example, this version of how traffic flows that I created using cats:
![3](https://user-images.githubusercontent.com/50714166/127528639-c2ab5be1-bf59-4974-9c3c-bf4d4c648618.png)

**Comment by Shoalsteed** [comment]
> **What is Included**
> 
> The text on this page doesn't feel jargon-y. I read through everything quite easily.
> 
> I2PSnark and The Address Book link to other pages. Those pages could be improved. For example, I2PSnark links to a page about trackers? The text doesn't seem relevant to I2PSnark, and I2PSnark is not mentioned once on there.
> 
> The links could be more obvious. The color, a dark gray, blends in with regular non-clickable text which is black.
> 
> Maybe screenshots or visuals to go along with each application? Might look messy on this page, however.

This page needs a glow up for sure , and I think that adding more images might be a good thing to.

**Comment by Shoalsteed** [comment]
> **How to Browse I2P**
> 
> This page is very similar to the post-install page. The Post-Install Work section is not there, but there is the Firefox Profile for Windows and How to configure your browser sections.
> 
> Will a user that has either already downloaded or not yet downloaded I2P need to access this page? I can see how someone that downloads but didn't complete installation would want to refer to the installation guide and know how to configure their browser. This page might not be useful for someone trying to learn about I2P.

This is where I think we may want to move some of the content in About to a new menu Item called Getting Started. So, this can be solved with some IA work. We can tackle that next , and in what order a guide would be?

**Comment by Shoalsteed** [comment]
@luciewho Can you add your feedback on the FAQ as well? I feel that the page has some issues, but I have looked at it so many times that I cannot see the solution.

**Comment by luciewho** [comment]
I agree, something like that high level graphic (cute cats!) with a short text description. Maybe a link at the bottom like,  developers - read more about how I2P works. Need to consider how developer and non-developer flows would look like in the IA. Is there a brand/style guideline that exists for visuals or graphics?

**Comment by luciewho** [comment]
Would you say that the priority is for the non-developer? Is that the major user base?

**Comment by Shoalsteed** [comment]
> I agree, something like that high level graphic (cute cats!) with a short text description. Maybe a link at the bottom like, developers - read more about how I2P works. Need to consider how developer and non-developer flows would look like in the IA. Is there a brand/style guideline that exists for visuals or graphics?

No, but we can make one =)

**Comment by Shoalsteed** [comment]
> Would you say that the priority is for the non-developer? Is that the major user base?

Onboarding new users / adoption is the priority.  People need to have a proper intro in order to take interest in contributing to the project I think.

New User/ 
Retention supporting docs ( Getting Started and Troubleshooting, community links) 

Contributor Onboarding:
Translators, 
Reseed Operatiors
Network Support  ( Mirror operators, etc) 

Dev Onboarding
Application Builders
Network / Cryptographers 

Researchers

**Comment by luciewho** [comment]
**FAQ**

Some of the questions also feel jargon-y. These questions are basic and feel like something I, as a casual user, would ask:
Is installing Java required to use I2P?
What is an "I2P Site?"
Most of the I2P Sites within I2P are down?
How do I configure my browser?
How do I set up my own I2P Site?

A question like this feels like something a developer would ask:
In wrapper.log I see an error that states "Protocol family unavailable" when loading the Router Console
How do I connect to IRC within I2P?
Why is I2P listening on port 32000?
Is it possible to block I2P?

The answers to many of the questions contain lots of jargon as well. I believe the FAQ should have questions that increase from less difficulty/complexity of concept to more towards the end. I will look for some examples of good FAQs, let me know if you have any in mind.

This is a UI note - the list of questions stays static at the top of the page, so when I go to question at the bottom of the page, I have to scroll back up every time to see the list. I'm not sure what the best UI would be, but I think this could be improved. Examples are to have the list move with the page or "back to top" link.

**Comment by luciewho** [comment]
> Onboarding new users / adoption is the priority. People need to have a proper intro in order to take interest in contributing to the project I think.
> 
> New User/
> Retention supporting docs ( Getting Started and Troubleshooting, community links)

Does new user mean people like journalists and activists? Does it include people that are developers but also new to I2P? How technical do you think the new user is or should be?

**Comment by Shoalsteed** [comment]
> > Onboarding new users / adoption is the priority. People need to have a proper intro in order to take interest in contributing to the project I think.
> > New User/
> > Retention supporting docs ( Getting Started and Troubleshooting, community links)
> 
> Does new user mean people like journalists and activists? Does it include people that are developers but also new to I2P? How technical do you think the new user is or should be?

new users would be people who have some sort of knowledge of privacy tools. As for specific groups ie journalists or activists, I do not feel that creating onboarding for specific use cases is a thing we can do without finding out if either of those groups
 1) use I2P so we can talk to them and how they do risk assessment. 
2) understand their environment and security or connection ability.
3) think it is a good idea at all to create specific personas. I feel conflicted about saying "use I2P if you are this person" since it an easy way for bad actors to more easily target specific people.

so in the end, it is maybe more about providing robust and clear product info and letting people figure out their use case beyond some simple things that we can provide. Like we can say "get your friends to join I2P and create your own secret sharing circle!" But I would not really feel comfortable saying "are you an activist - use I2P" since I cannot also provide proper security advice if that is needed.

**Comment by luciewho** [comment]
Gotcha, that makes sense!!

**Comment by Shoalsteed** [comment]
i think that there is an opportunity here to do some research though for the needs of journalists, maybe do some user testing with them.

The other thing I did not mention is that the more mundane user traffic, the better. it adds to everyone's traffic protection .

**Comment by Shoalsteed** [comment]
> **FAQ**
> 
> Some of the questions also feel jargon-y. These questions are basic and feel like something I, as a casual user, would ask:
> Is installing Java required to use I2P?
> What is an "I2P Site?"
> Most of the I2P Sites within I2P are down?
> How do I configure my browser?
> How do I set up my own I2P Site?
> 
> A question like this feels like something a developer would ask:
> In wrapper.log I see an error that states "Protocol family unavailable" when loading the Router Console
> How do I connect to IRC within I2P?
> Why is I2P listening on port 32000?
> Is it possible to block I2P?
> 
> The answers to many of the questions contain lots of jargon as well. I believe the FAQ should have questions that increase from less difficulty/complexity of concept to more towards the end. I will look for some examples of good FAQs, let me know if you have any in mind.
> 
> This is a UI note - the list of questions stays static at the top of the page, so when I go to question at the bottom of the page, I have to scroll back up every time to see the list. I'm not sure what the best UI would be, but I think this could be improved. Examples are to have the list move with the page or "back to top" link.

There is a big opportunity to consider how this information is displayed, and how and for whom. 
Are there questions aside from what is above that you would add?
For sorting is it Software questions, Network questions, Privacy/ security Questions? Can these categories be renamed in a way that is more engaging? 
Also, I think I would like to add something that makes it clear regarding how protocols protect, the rest is your own threat model and operational security / risk management. 

regarding the UI, yes, that is annoying! Are you familiar with CSS? If so, we can create patches for things like this.

**Comment by luciewho** [comment]
The categories definitely can be renamed. They are currently jargon-y and don't feel accessible. They are: I2P Router Help, Configuration, Reseeds, Privacy-Safety, Internet Access/Performance, Bugs and Questions. Your suggestions are better. It could look something like: Software (or Intro to I2P? I2P Basics?), Configuration, Network, Privacy and Security, and the protocols protection you mentioned. 

Some other questions that could be useful on the FAQ:
Is I2P for me? or Why should I use I2P?
How does I2P compare with other private internets like Tor or Freenet? (Can link to those comparison pages that already exist)
What does I2P not do?
What is outproxy? (Can have that outproxy disclaimer that's on the post-install page)
What can I do with I2P?
Why is ___ not working? (Can direct to the troubleshooting page)
What does ___ mean? (Can direct to glossary)
How can I contribute to I2P? 

I know some CSS but mostly basic stuff. Let me know what I can do to help!

**Comment by Shoalsteed** [comment]
> **How to Browse I2P**
> 
> This page is very similar to the post-install page. The Post-Install Work section is not there, but there is the Firefox Profile for Windows and How to configure your browser sections.
> 
> Will a user that has either already downloaded or not yet downloaded I2P need to access this page? I can see how someone that downloads but didn't complete installation would want to refer to the installation guide and know how to configure their browser. This page might not be useful for someone trying to learn about I2P.

yes, I would like to keep this accessible to anyone. It also helps set a person's expectations about what they will need to do to use I2P. additionally, It reinforces that I2P is its own network

**Comment by Shoalsteed** [comment]
> **FAQ**
> 
> Some of the questions also feel jargon-y. These questions are basic and feel like something I, as a casual user, would ask:
> Is installing Java required to use I2P?
> What is an "I2P Site?"
> Most of the I2P Sites within I2P are down?
> How do I configure my browser?
> How do I set up my own I2P Site?
> 
> A question like this feels like something a developer would ask:
> In wrapper.log I see an error that states "Protocol family unavailable" when loading the Router Console
> How do I connect to IRC within I2P?
> Why is I2P listening on port 32000?
> Is it possible to block I2P?
> 
> The answers to many of the questions contain lots of jargon as well. I believe the FAQ should have questions that increase from less difficulty/complexity of concept to more towards the end. I will look for some examples of good FAQs, let me know if you have any in mind.
> 
> This is a UI note - the list of questions stays static at the top of the page, so when I go to question at the bottom of the page, I have to scroll back up every time to see the list. I'm not sure what the best UI would be, but I think this could be improved. Examples are to have the list move with the page or "back to top" link.

I really do not have any examples of good FAQ's - so if you have any you like, let me know!

**Comment by Shoalsteed** [comment]
> The categories definitely can be renamed. They are currently jargon-y and don't feel accessible. They are: I2P Router Help, Configuration, Reseeds, Privacy-Safety, Internet Access/Performance, Bugs and Questions. Your suggestions are better. It could look something like: Software (or Intro to I2P? I2P Basics?), Configuration, Network, Privacy and Security, and the protocols protection you mentioned.
> 
> Some other questions that could be useful on the FAQ:
> Is I2P for me? or Why should I use I2P?
> How does I2P compare with other private internets like Tor or Freenet? (Can link to those comparison pages that already exist)
> What does I2P not do?
> What is outproxy? (Can have that outproxy disclaimer that's on the post-install page)
> What can I do with I2P?
> Why is ___ not working? (Can direct to the troubleshooting page)
> What does ___ mean? (Can direct to glossary)
> How can I contribute to I2P?
> 
> I know some CSS but mostly basic stuff. Let me know what I can do to help!

For sure - we introduce i2P specific language too soon I think , or to up front. Reseeds, or other things that have to do with how you connect to the I2P network could go under a topic called Connection.

As for CSS, yes, let's get to that next week! There are probably places on the site that should/ can benefits from some work.

**Comment by luciewho** [comment]
**Applications** 

The first page under Applications, Bittorrent, looks like it's the same page that I2PSnark leads to on the [What Is Included page ](https://geti2p.net/en/about/software)

All of the sub-pages under Applications feel like they are written for developers. Would new users care about these applications?

**Comment by luciewho** [comment]
I think some of the pages under Guide to I2P Software and Help could be re-organized or the copy (of the page names) could be refined. Intro, Guide, and Help all seem to mesh together. (example: FAQ and Help seem to be used interchangeably on other websites. Could be redundant copy on I2P.)

Three levels of menus is also a bit much, but maybe that's just me? Two at most feels better and you're less likely to get lost. If you move your cursor by a little you lose your place and have to search through the pages again.

![Screen Shot 2021-07-29 at 2 58 29 PM](https://user-images.githubusercontent.com/6728799/127571640-8b1258ce-ae0b-4978-ab33-ea187cb6244a.png)

**Comment by Shoalsteed** [comment]
> **Applications**
> 
> The first page under Applications, Bittorrent, looks like it's the same page that I2PSnark leads to on the [What Is Included page ](https://geti2p.net/en/about/software)
> 
> All of the sub-pages under Applications feel like they are written for developers. Would new users care about these applications?

They really are more dev focused.
The issue that we used to have was that we had a long menu , so in an effort to reduce things, more general guides all were put in the about section. Not sure how to remedy that without assessing the entire structure of the landing page.

In the meantime, this info should be renamed / dealt with differently.

**Comment by Shoalsteed** [comment]
> I think some of the pages under Guide to I2P Software and Help could be re-organized or the copy (of the page names) could be refined. Intro, Guide, and Help all seem to mesh together. (example: FAQ and Help seem to be used interchangeably on other websites. Could be redundant copy on I2P.)
> 
> Three levels of menus is also a bit much, but maybe that's just me? Two at most feels better and you're less likely to get lost. If you move your cursor by a little you lose your place and have to search through the pages again.
> 
> ![Screen Shot 2021-07-29 at 2 58 29 PM](https://user-images.githubusercontent.com/6728799/127571640-8b1258ce-ae0b-4978-ab33-ea187cb6244a.png)

I think lots of this needs to be consolidated. We did a big clean up last year, but it is time to do another pass.
