### ISSUE TITLE
Style Guide

### ISSUE THREAD

**Issue by luciewho** [Shoalsteed/UX#20]
Branding and style guidelines for the website, based on what it currently looks like.

**Comment by Shoalsteed** [comment]
here is a limited stye guide that Ura created for us https://ura.design/projects/i2p

we can expand from that

**Comment by Shoalsteed** [comment]
I think that for the install guides:
-they should use the I2P blue for a background
-use a stylized toopie for a guide
-not use emojis

**Comment by Shoalsteed** [comment]
![2](https://user-images.githubusercontent.com/50714166/128930985-bbc60c88-8cfa-47d5-b4b4-d1714030bc1f.png)
![3](https://user-images.githubusercontent.com/50714166/128930988-cc85a662-cec2-4f5b-90cb-675248e047d5.png)
![4](https://user-images.githubusercontent.com/50714166/128930990-4d1686ce-b2e4-41ec-81a9-b08f25fe54b5.png)
![5](https://user-images.githubusercontent.com/50714166/128930991-fc6652b6-8b5b-4a9f-a7e7-6c1846e32905.png)
![6](https://user-images.githubusercontent.com/50714166/128930992-1806b716-93a7-46d3-9d63-b550e38bf1cf.png)
![7](https://user-images.githubusercontent.com/50714166/128930993-6e348660-438a-4134-acfc-6d9ef1c0a218.png)
![8](https://user-images.githubusercontent.com/50714166/128930994-61ebb742-99fe-4e73-8a91-8f660c795821.png)
![9](https://user-images.githubusercontent.com/50714166/128930996-8d57e43d-8340-485f-9660-bbfcf6c2bde1.png)
![11](https://user-images.githubusercontent.com/50714166/128930998-930e74f1-eb8c-4f72-934c-bd22964a2b3a.png)
![12](https://user-images.githubusercontent.com/50714166/128931001-380435cf-9960-4012-b0d4-6a82f264b6a4.png)
![13](https://user-images.githubusercontent.com/50714166/128931002-2571acc9-bfb1-4fdf-a986-b2e1c3f98f1f.png)
![14](https://user-images.githubusercontent.com/50714166/128931003-c3c731a3-a4fa-41e9-af9b-900f88ecccd9.png)
![15](https://user-images.githubusercontent.com/50714166/128931004-545eba74-43c7-4647-bdf6-800e304e3aeb.png)
![16](https://user-images.githubusercontent.com/50714166/128931007-2f5f91f5-e48b-40cf-b991-f93453333fb6.png)
![17](https://user-images.githubusercontent.com/50714166/128931011-7ceff7e6-aec0-4876-b8d1-1ef15f180865.png)
![18](https://user-images.githubusercontent.com/50714166/128931012-5e3e9eca-b176-4f1e-853a-29664044c2fe.png)
![19](https://user-images.githubusercontent.com/50714166/128931014-6304f23b-7db5-4389-94a4-2f8dbcfe8c08.png)
![20](https://user-images.githubusercontent.com/50714166/128931016-2a103d45-3e26-4818-b240-0e7b51a2dfc3.png)
![21](https://user-images.githubusercontent.com/50714166/128931017-1e3258f4-e59c-44fb-872c-8739155aa34c.png)

**Comment by luciewho** [comment]
Curious about I2P blue. Is that #4661A9 on the Ura site?

While making the wireframes I noticed there were multiple purple colors going on, with different HEX codes. 
the background for the installation steps above (#0B0468)
the background on the installation guide on Medium (#363A68)
the lighter purple around the OS box (#546BD2)
the dark purple for sig mirror button (#3C468A)
the purple used for the OS icon (#4661A9)
the purple line underneath the main menu (#4356B7) 

I don't see anything about purple in the Ura guide. Do you know which HEX code(s) for purple should be used? It seems like a lot, maybe up to 2 purples would be good. I'm guessing it might be something we'll have to add to the style guide.

<img width="685" alt="Screen Shot 2021-08-10 at 1 51 32 PM" src="https://user-images.githubusercontent.com/6728799/128933346-d806d20a-faea-4eb8-b09f-50975af3827c.png">

<img width="789" alt="Screen Shot 2021-08-10 at 1 53 47 PM" src="https://user-images.githubusercontent.com/6728799/128934247-940e2b06-b604-455f-9f3a-b45fd86121ef.png">

**Comment by Shoalsteed** [comment]
that is strange that the colour turns out differently between the install / Medium since it is the same slide deck.

The Ura purple/blue is the colour we want #4661A9
#363A68 would be the other option

**Comment by luciewho** [comment]
weird, maybe the color appears different on my computer or the color detector I used. 

okay good to know. do you think some the other purples that are being used should be changed?

**Comment by Shoalsteed** [comment]
I think that they should 

:root {
    --i2poffblack: #070425;
    --i2poffwhite: #f6f6fa;
    --i2ppurple: #222187;
    --i2pmidblue: #265ea7;
    --i2plightblue: #9dabd5;
    --i2pdarkblue: #2d4470;
    --i2plightgreen: #709fa6;
    --i2pmossy: #60ab60;
    --i2pctablue: #00ffff;
    --i2pgrey: #333333;
    --i2pbggrey: #9e9e9e;
    --i2pcharcoal: #080808;
 border: 2px solid #4456B7

Above are most of the colours displayed on the site.
I would be open to creating a new style guide since the one that was created by Ura is limited.

**Comment by Shoalsteed** [comment]
> weird, maybe the color appears different on my computer or the color detector I used.
> 
> okay good to know. do you think some the other purples that are being used should be changed?

The download page for sure has 3 purples!

**Comment by luciewho** [comment]
Leaving this resource here for inspo: 

https://teenyicons.com
https://feathericons.com
https://remixicon.com

Might need to create some icons in the future for the Resources page and other pages as well

**Comment by Shoalsteed** [comment]
@luciewho 
Here is the extended guide that Ura made when we were doing alternative logo explorations. Many more colours to choose from in my Pacific/ Summer/ Desert palette lol ( my inspo was https://claystreetca.com/collections/horizon-series) 
https://uracreative.github.io/i2p-styleguide/design/

**Comment by luciewho** [comment]
Starting to put together a style guide. And applying some of the styles from Ura (like the typography and the colors) to the installation wireframe. So far, just one of the download pages (page 2) has the applied colors and fonts.

[Style Guide Wireframe.pdf](https://github.com/Shoalsteed/UX/files/6984189/Style.Guide.Wireframe.pdf)

**Comment by luciewho** [comment]
I don't want to copy Mullvad too much, but I like how there's two contrasting backgrounds on the Download page, blue on the top and white on the bottom. It breaks up the sections well. Just something to think about.

https://mullvad.net/en/download/macos/

**Comment by Shoalsteed** [comment]
I like this too - I think we should do it as well.

**Comment by Shoalsteed** [comment]
![wizard1](https://user-images.githubusercontent.com/50714166/129949160-94e89de4-fabd-4ab1-a372-30a4077b1b16.png)
![wizard2](https://user-images.githubusercontent.com/50714166/129949164-eacc7f86-09b6-4cfa-ba31-9e4b587df03a.png)

different highlighting option

**Comment by Shoalsteed** [comment]
![1](https://user-images.githubusercontent.com/50714166/129950585-0a281bef-f60c-4529-afad-59b1fa3920b8.png)
![2](https://user-images.githubusercontent.com/50714166/129950589-3aaafab5-6e1d-4ac0-be9d-161561762a54.png)
![3](https://user-images.githubusercontent.com/50714166/129950591-ce9f4f7e-8b01-42b1-b222-e3c3a4d9e1ea.png)

**Comment by Shoalsteed** [comment]
highlights or circles?

**Comment by Shoalsteed** [comment]
** for style guide: when creating screenshots always ensure to use as close to "factory settings" as possible - do not show something that will give away any unique identifiers.

**Comment by luciewho** [comment]
I would like to see the green line circles less thick, right around the actual button to click rather than the area. The double circles is confusing because you don't know what you're supposed to focus on.

The highlight looks cool. Would like to see the visual-ness of it cleaned up (it highlights the space slightly outside the box/pop-up and sometimes the width around it is not consistent. Having it match the exact size of the box might look better). I also think using it to point out an area is better, whereas using the lined circles to point out a button to click is better. The highlight isn't as impactful when gesturing what button to click on. 

Having two styles could be confusing though. I would ultimately go with the line circles because it's familiar, doesn't blend in or look like it's part of the installer. I think the line circles just need to be cleaned up in terms of thickness and where it is placed on the button/area.

**Comment by luciewho** [comment]
I'm testing out different background colors for the Download page in that Mullvad style. The free speech blue would be nice but it's really hard to read black text on it and I don't like the white text on it that much either. 

<img width="769" alt="Screen Shot 2021-08-18 at 12 10 47 PM" src="https://user-images.githubusercontent.com/6728799/129957831-9c999bd6-f338-4fe5-9c59-65d7361cb711.png">
<img width="767" alt="Screen Shot 2021-08-18 at 12 05 16 PM" src="https://user-images.githubusercontent.com/6728799/129957440-6a70ea07-19d5-4160-960c-18dc47a939c7.png">
<img width="768" alt="Screen Shot 2021-08-18 at 12 05 26 PM" src="https://user-images.githubusercontent.com/6728799/129957450-e1d99a47-54bd-43b7-846d-c4ca74970453.png">
<img width="771" alt="Screen Shot 2021-08-18 at 12 06 04 PM" src="https://user-images.githubusercontent.com/6728799/129957458-2132545f-3699-419d-8d76-74532ae91fd1.png">
<img width="769" alt="Screen Shot 2021-08-18 at 12 05 35 PM" src="https://user-images.githubusercontent.com/6728799/129957461-f1268ae2-add7-4350-b7b6-8483eeaac7f9.png">

I think the all white or cream/white work best. Or we find a new secondary color to replace the teal.

**Comment by Shoalsteed** [comment]
I really am most drawn to the dark purple.

**Comment by Shoalsteed** [comment]
![1](https://user-images.githubusercontent.com/50714166/129979677-57e11df3-aab3-4317-9138-cca0c4adc88e.png)

**Comment by Shoalsteed** [comment]
I do not normally like this sort of thing, but felt compelled to make one. looking for ways to illustrate something like this

**Comment by luciewho** [comment]
> I really am most drawn to the dark purple.

You don't think the white text is hard to read over the dark background? I am not sure about starting with a cream background and then it changing to dark purple. 

I wanna get an opinion from a visual/UI friend who works with more graphic stuff than me and see what they think about the background colors and the green circles as well.

**Comment by luciewho** [comment]
Separate buttons for mirror/sig. 

<img width="236" alt="Screen Shot 2021-08-19 at 8 30 26 AM" src="https://user-images.githubusercontent.com/6728799/130097215-479fee0b-d924-469f-821a-dd7e32c5ef00.png">
<img width="358" alt="Screen Shot 2021-08-19 at 8 35 22 AM" src="https://user-images.githubusercontent.com/6728799/130098146-e607d935-e90c-4eac-8ad0-caf9f772a3ff.png">
<img width="252" alt="Screen Shot 2021-08-19 at 8 30 36 AM" src="https://user-images.githubusercontent.com/6728799/130097247-f847d307-8bf3-481a-a8a7-6e7d05711239.png">
<img width="274" alt="Screen Shot 2021-08-19 at 8 30 45 AM" src="https://user-images.githubusercontent.com/6728799/130097276-bf20b8ee-2e44-4829-bcee-d94edd7b9576.png">


I think the first or second one looks best when on the page. For the second one, would need to introduce a hover state (like half of it turns to solid colored button) to make it obvious that it is 2 buttons.

**Comment by Shoalsteed** [comment]
> > I really am most drawn to the dark purple.
> 
> You don't think the white text is hard to read over the dark background? I am not sure about starting with a cream background and then it changing to dark purple.
> 
> I wanna get an opinion from a visual/UI friend who works with more graphic stuff than me and see what they think about the background colors and the green circles as well.

the second ura guide shows a score of readability for text on different backgrounds for reference.

**Comment by Shoalsteed** [comment]
> Separate buttons for mirror/sig.
> 
> <img alt="Screen Shot 2021-08-19 at 8 30 26 AM" width="236" src="https://user-images.githubusercontent.com/6728799/130097215-479fee0b-d924-469f-821a-dd7e32c5ef00.png">
> 
> <img alt="Screen Shot 2021-08-19 at 8 35 22 AM" width="358" src="https://user-images.githubusercontent.com/6728799/130098146-e607d935-e90c-4eac-8ad0-caf9f772a3ff.png">
> 
> <img alt="Screen Shot 2021-08-19 at 8 30 36 AM" width="252" src="https://user-images.githubusercontent.com/6728799/130097247-f847d307-8bf3-481a-a8a7-6e7d05711239.png">
> 
> <img alt="Screen Shot 2021-08-19 at 8 30 45 AM" width="274" src="https://user-images.githubusercontent.com/6728799/130097276-bf20b8ee-2e44-4829-bcee-d94edd7b9576.png">
> 
> I think the first or second one looks best when on the page. For the second one, would need to introduce a hover state (like half of it turns to solid colored button) to make it obvious that it is 2 buttons.

agree! My choices too

**Comment by Shoalsteed** [comment]
> > I really am most drawn to the dark purple.
> 
> You don't think the white text is hard to read over the dark background? I am not sure about starting with a cream background and then it changing to dark purple.
> 
> I wanna get an opinion from a visual/UI friend who works with more graphic stuff than me and see what they think about the background colors and the green circles as well.

sure - it is a good idea.
I think that others have managed well with using colours on backgrounds. The issue I would see is if it makes things look too cartoon-y . I am on board with what choice is best for readability.

**Comment by luciewho** [comment]
Got some good feedback on the styling by some visual designers:

1 - Liked the dark purple+white because of high contrast. Also thought the green lined circles were more contrasting and easier to read than the highlights.
2 - Preferred the dark purple+white, but not the cream+white. Thought the cream looked dated, a light gray would look better.
3 - Preferred the cream+white. Not the all-white because tabbing feature wasn't as obvious. Did not like the dark purple+white because the text was hard to read, background too dark. Eye was drawn toward white text instead of green download button. Java icon hard to read. 

Nobody liked the dark purple+cream. I tried to use the cream because it is already the main bg color. It would be strange to introduce dark purple and white as new background colors when it's cream everywhere else.

I think we essentially need to pick a new background color or stick with the cream. It could be a slightly lighter-colored purple.
Also, Mullvad does it well because they have the entire top page including the header as the blue color. Every page has a blue header and white background below for text. They keep the colors consistent.

Hope this made sense. Let's discuss on Monday!

**Comment by Shoalsteed** [comment]
Good feedback, especially about where the eye is drawn too ( which may not be what we want people to focus on!)

**Comment by luciewho** [comment]
Trying to find some open sources images we could use for the illustration/graphic on the download page. I am not skilled at making something from scratch, but here are some options we can pull from. Will add more as I come across them:

https://lucid.pixsellz.io/?ref=uistore.design
https://thenounproject.com

**Comment by Shoalsteed** [comment]
> Trying to find some open sources images we could use for the illustration/graphic on the download page. I am not skilled at making something from scratch, but here are some options we can pull from. Will add more as I come across them:
> 
> https://lucid.pixsellz.io/?ref=uistore.design
> https://thenounproject.com

graphic assets are pretty hard to find. The best I have come across is Canva. I am working on something there .

**Comment by luciewho** [comment]
I like how ExpressVPN does the Language tab, 3 columns of languages in a box. 

![Screen Shot 2021-08-23 at 1 50 07 PM](https://user-images.githubusercontent.com/6728799/130517600-51bb4889-a711-40c6-a9f3-f6d47edaecb9.png)

**Comment by Shoalsteed** [comment]
this is way better

**Comment by Shoalsteed** [comment]
Logos : https://github.com/uracreative/works/tree/main/I2P
toopie https://en.wikipedia.org/wiki/File:Itoopie.svg

**Comment by luciewho** [comment]
Colors in style guide so far. (I think I will remove the light gray and use what is marked as medium gray -- which is the color of the screenshot backgrounds)

Maybe we need another color for an "alternate" button that is not the secondary button (with the outline)

<img width="968" alt="Screen Shot 2021-09-01 at 10 55 32 AM" src="https://user-images.githubusercontent.com/6728799/131720301-0610e6a2-bf70-462f-a367-fd8f66e4613d.png">

<img width="306" alt="Screen Shot 2021-09-01 at 11 00 01 AM" src="https://user-images.githubusercontent.com/6728799/131720697-98b218d5-0fb9-4d27-b211-4e21938ae3e0.png">

**Comment by Shoalsteed** [comment]
![oldlogo](https://user-images.githubusercontent.com/50714166/133677420-ed7fa5b2-d6e6-41f4-8c18-87d4861deba4.png)
old logo 
![poster](https://user-images.githubusercontent.com/50714166/133677459-63a6361c-576b-43f0-a6ea-888ab34d01ee.jpeg)
old poster ( no idea who made it)

**Comment by Shoalsteed** [comment]
all logos can be downloaded from here for the new logo https://github.com/uracreative/works/tree/main/I2P

**Comment by luciewho** [comment]
Inspiration for style guides on websites

http://styleguides.io/examples
http://codeforamerica.clearleft.com
http://ux.mailchimp.com/patterns/typography
https://govuk-elements.herokuapp.com/colour/

**Comment by Shoalsteed** [comment]
here is one that I like https://foundation.mozilla.org/en/style-guide/

**Comment by Shoalsteed** [comment]
@luciewho do you have a PDF of the style guide prepared? How close is this to being completed?

**Comment by luciewho** [comment]
This is pretty close. Let's talk about this on Friday with idk because there is some stuff regarding the CSS.
