### ISSUE TITLE
FAQ

### ISSUE THREAD

**Issue by Shoalsteed** [Shoalsteed/UX#21]
**FAQ**
_Considerations for improved information flow and improved accessibility_ 

**The I2P Ecosystem**
What is I2P?
Why should I use I2P?
What does it do?
What does I2P not do?
How is it different from the Internet?
How does I2P compare with other private internets like Tor or Freenet? (Can link to those comparison pages that already exist)
What do you mean by Invisible or Private?
What is an I2P site?
What does Peer to Peer mean?
What can I do with the software?
What does reseed mean?
What is outproxy? (Can have that outproxy disclaimer that's on the post-install page)
Bandwidth Sharing

**Comment by Shoalsteed** [comment]
**Connecting and Connection Issues**

add a screenshot of the sidebar 
add messages and what they mean and how to fix them

![Screen Shot 2021-07-29 at 3 47 05 PM](https://user-images.githubusercontent.com/50714166/127560027-0178d68f-985e-461b-a9b2-3f2069dc98d8.png)

![Screen Shot 2021-07-29 at 3 47 12 PM](https://user-images.githubusercontent.com/50714166/127560064-65d93db3-1229-412b-b1ad-f83afbee48fd.png)
![Screen Shot 2021-07-29 at 3 47 23 PM](https://user-images.githubusercontent.com/50714166/127560065-b86944a6-c38c-46e8-8eac-bc499a31a723.png)
![Screen Shot 2021-07-29 at 3 47 33 PM](https://user-images.githubusercontent.com/50714166/127560066-ef0c5e04-694e-4c05-b7e0-a0b3c29a8b2a.png)
![Screen Shot 2021-07-29 at 3 47 39 PM](https://user-images.githubusercontent.com/50714166/127560067-e2c17efb-1581-4e7f-a252-cfb1b47c9abc.png)
![Screen Shot 2021-07-29 at 3 47 51 PM](https://user-images.githubusercontent.com/50714166/127560068-598c0533-9052-4272-9de3-8164a9fbf89c.png)

This is what it would look like ( needs better descriptions!)
![1](https://user-images.githubusercontent.com/50714166/127563145-81584de8-a9e0-411a-ab6d-f422df43f5c9.png)
![2](https://user-images.githubusercontent.com/50714166/127563147-f280afd2-6e9d-407b-b14b-48f66c1497bf.png)

This way we can include the troubleshooting info here as needed

**Comment by Shoalsteed** [comment]
**Privacy and Safety**

**Comment by Shoalsteed** [comment]
**Advanced Connection Questions and Troubleshooting** 

NAT / Firewall
Is it possible to use I2P as a SOCKS proxy?
How can I access the web console from my other machines or password protect it?
What ports does I2P use?
Why is I2P listening for connections on port 32000?
Is it possible to block I2P?
In wrapper.log I see an error stating Protocol family unavailable when I2P is loading
What systems will I2P run on?
What about "De-Anonymizing" attacks?

**Comment by luciewho** [comment]
Thought this was a good example of FAQ with technical information: https://aws.amazon.com/faqs/

They have separate FAQ pages for different categories. That might be too much for I2P, unless we do something like an FAQ for new users and FAQ for developers.

One of the FAQ pages: https://aws.amazon.com/ec2/faqs/
I like that they call the first section "General". There are also sub-categories under General. 
The side bar is sticky and stays on the page as you're scrolling through the questions. 

AWS has a lot of different products/technologies but it is organized well. The questions and answers do seem targeted toward developers or people with technical knowledge (jargon). But the answers are not overwhelmingly long.

**Comment by Shoalsteed** [comment]
I think that the structure of that example is worth trying to achieve at the scale we require. As it is we have troubleshooting , advanced user questions, general questions and privacy questions all lumped into one FAQ which is not deal. 

The other idea is to move any info that has to do with router, p2p, etc into something like above and call it something other than a FAQ, then look at what is left and sort that?

**Comment by luciewho** [comment]
Another interesting FAQ example: https://help.instagram.com
This one has very prominent hierarchy of questions/information and is visually appealing: https://www.airbnb.com/help/home

**Comment by luciewho** [comment]
> I think that the structure of that example is worth trying to achieve at the scale we require. As it is we have troubleshooting , advanced user questions, general questions and privacy questions all lumped into one FAQ which is not deal.
> 
> The other idea is to move any info that has to do with router, p2p, etc into something like above and call it something other than a FAQ, then look at what is left and sort that?

Good point. I will put together some wireframe options for the FAQ!

**Comment by luciewho** [comment]
> The other idea is to move any info that has to do with router, p2p, etc into something like above and call it something other than a FAQ, then look at what is left and sort that?

This example seems similar to what you're talking about: https://disneyworld.disney.go.com/help/
They have an FAQ and Privacy & Legal, etc in the sidebar but there are other categories like Annual Passes, etc which have their own FAQ. It all falls under this big umbrella called Help Center. Interesting way of organizing. The icons and white space make it feel less dense too.

**Comment by Shoalsteed** [comment]
**Categories:**

_Getting Started_
  - install
  - browser set up 
  - advanced set up ( outproxy/ NAT)
  - sigs & GPG
  - introduce router and applications
  - outproxy

_Network Connection Guide & Troubleshooting_
- all error messages and sidebar alerts /what they mean and what to do

_Questions About I2P_

_About the I2P Network_
- reseeds
- bandwidth
- why it is slow
- Privacy related topics

**Contributors Guides**
- reseed operators
- mirrors
- translators

**Comment by Shoalsteed** [comment]
Trying to map out FAQ and other items from the About drop down menu:

![1](https://user-images.githubusercontent.com/50714166/128763369-790ae2d3-9c23-4189-8d40-d8fb78b061e3.png)
![2](https://user-images.githubusercontent.com/50714166/128763370-dc522bf1-1611-44a5-a4a9-111da59507d0.png)

**Comment by luciewho** [comment]
Thanks! I've been building that Support page and will incorporate this into the wireframe. I'm wondering, if we remove the term FAQ, what would be a better alternative label for those categories? Could they even be collapsed under one title or label, maybe needs multiple labels?

**Comment by luciewho** [comment]
This is what the Support (I called it Resources in the main menu actually) page looks like so far (similar to the Workiva page). I made some assumptions for each box/category so they could organized differently. And the FAQ/About categories you put together above could be incorporated. 

<img width="873" alt="Screen Shot 2021-08-10 at 10 26 23 AM" src="https://user-images.githubusercontent.com/6728799/128906577-75ef7df6-0349-4d78-996f-1905af70c1ad.png">

I also changed the categories in the main menu to work better with this new organization.
<img width="400" alt="Screen Shot 2021-08-10 at 10 28 54 AM" src="https://user-images.githubusercontent.com/6728799/128906821-87b4029d-0cd5-469d-a1c0-e591ed55fcda.png">

**Comment by Shoalsteed** [comment]
> Thanks! I've been building that Support page and will incorporate this into the wireframe. I'm wondering, if we remove the term FAQ, what would be a better alternative label for those categories? Could they even be collapsed under one title or label, maybe needs multiple labels?

Good question. I think that Troubleshooting Your Network Connections, Get to Know The I2P Software, Get to know the I2P network, are better approaches. I guess being clear and creating clear categories for people to look at rather than lumping stuff as we have into an FAQ. That is what I am doing right now is trying to assess the info we have and seeing where it could go to make more sense.
Maybe it is simply I2P Network, I2P Software, and I2P support?
When I think of an FAQ, I think of it almost like a junk shop or place for things that could or should be better integrated into onboarding.

**Comment by Shoalsteed** [comment]
Regarding the wireframe:
I love the layout!

**Comment by Shoalsteed** [comment]
this whole consolidation thing is part of my sorting attempts above https://github.com/Shoalsteed/UX/issues/19#issuecomment-889518860

**Comment by luciewho** [comment]
I put together a few versions of how the Resources page could look with the FAQ/About categories from above. version 1 versus version 2 are the latest versions, version 0 is just what I had screenshot above.

There's a few other wireframes like what the page might look like when you click on a box. 

Let me know your thoughts!

[Resources.pdf](https://github.com/Shoalsteed/UX/files/6964561/Resources.pdf)

**Comment by Shoalsteed** [comment]
I am partial to Version 1, since in Version 2, the information seems too dense. 
Much easier visual gateway to actually seeing the categories!

**Comment by luciewho** [comment]
Some versions for the Resources pages. The best version will probably be contingent on the amount of information/copy there will be on the website.

[Resources.pdf](https://github.com/Shoalsteed/UX/files/6985758/Resources.pdf)

**Comment by Shoalsteed** [comment]
from Lucie:

FAQ

Some of the questions also feel jargon-y. These questions are basic and feel like something I, as a casual user, would ask:
Is installing Java required to use I2P?
What is an "I2P Site?"
Most of the I2P Sites within I2P are down?
How do I configure my browser?
How do I set up my own I2P Site?

A question like this feels like something a developer would ask:
In wrapper.log I see an error that states "Protocol family unavailable" when loading the Router Console
How do I connect to IRC within I2P?
Why is I2P listening on port 32000?
Is it possible to block I2P?

The answers to many of the questions contain lots of jargon as well. I believe the FAQ should have questions that increase from less difficulty/complexity of concept to more towards the end. I will look for some examples of good FAQs, let me know if you have any in mind.

**Comment by Shoalsteed** [comment]
the FAQ has been split into 3 pages - closing this so we do not get confused.
