### ISSUE TITLE
Research

### ISSUE THREAD

**Issue by luciewho** [Shoalsteed/UX#22]
Research Plan
Research and Interview Questions
Goals of Research
Users/People we want to target
Existing Research

**Comment by luciewho** [comment]
Put this together to have all the research in one place. Includes info I gathered from chatting with Sadie and idk, dug up from past issues. 

I took a stab at the proto-persona for a new user, answering those 3 questions (second to last page). @Shoalsteed curious how would you answer those questions? 

Anything else you want to add to the rest of the pages?

[Research.pdf](https://github.com/Shoalsteed/UX/files/6920157/Research.pdf)

**Comment by luciewho** [comment]
I think there are two subtypes of the New User persona. 

1.t he serious new user (someone that is like the journalist or activist)
2. the casual new user (someone that's non-technical and curious about privacy tools, using it for BitTorrent) 

![Screen Shot 2021-08-03 at 5 10 20 PM](https://user-images.githubusercontent.com/6728799/128101821-b12f1d0e-3ec6-40f3-9838-4af53cfe0986.png)

![Screen Shot 2021-08-03 at 5 10 16 PM](https://user-images.githubusercontent.com/6728799/128101826-a726bc82-6a2d-4d55-b05e-7455ecfd66c2.png)

**Comment by Shoalsteed** [comment]
1.the serious new user (someone that is like the journalist or activist)

I would include privacy/ decentralized / BTC / blockchain contributors to this list

Perhaps choose a different word for serious - maybe Users with Specific needs and interests?

**Comment by Shoalsteed** [comment]
Some issues for casual users :
-delineation issues / admin like assumptions 
( see https://www.reddit.com/r/i2p/comments/owzc37/help_me_understand_i2p_i2p_vs_i2pd_ports_bob_vs/ )
-being presented with information that conflates tasks/ workflows with PROJECT info
-being overwhelmed with configuration ( will be solved by improving the install process)
-sharing and bandwidth and Peer to Peer - these are not familiar to some people and can give pause

**Comment by Shoalsteed** [comment]
Issues for users who have specific privacy needs or are privacy tool contributors and builders:

-the menu that includes docs about protocol, app development/ libraries, network, crypto and research papers is jammed together. The menu itself acts in a way that makes it easy to lose your place.
-hard to find docs
-redundant information
-for community, people seem to find their way to reddit which is great because IDK has worked really hard to make that a supportive place. However, there are crypto meetings, and potentially community sprints and usability meetings that could be advertised better on the site. I propose a calendar of monthly meetings. The issue I am pointing out is involvement and access to the right team / topics in a more inviting and visible way.
-better placement of libraries and perhaps improved docs
-just poor information hierarchy in general that is hard to find and hard to read and in some places outdated

**Comment by luciewho** [comment]
@Shoalsteed can you explain what these terms (from above) mean? I don't fully understand.

> delineation issues / admin like assumptions
> being presented with information that conflates tasks/ workflows with PROJECT info

can you explain the delineation and admin like assumptions part?
what is "PROJECT info"?

> better placement of libraries 

what are libraries?

**Comment by Shoalsteed** [comment]
> @Shoalsteed can you explain what these terms (from above) mean? I don't fully understand.
> 
> > delineation issues / admin like assumptions
> > being presented with information that conflates tasks/ workflows with PROJECT info
> 
> can you explain the delineation and admin like assumptions part?
> what is "PROJECT info"?
> 
> > better placement of libraries
> 
> what are libraries?

For the delineation issues and admin like assumptions: this refers to the issues in the documentation where we imply musch more need to adjust things or assume that a new user is a developer and will want to use parts of the software that maybe an average user would not care about or ever need. Also, we tend to talk about many things at once in some places, which can leave a person feeling like they need to know more that they may need to.

For project -what I am referring to here an onboarding issue. In the past the call t action to download the software has been conflated with trying to get people to work on the project , or contribute in some way. This is why I refer to project and product.

The libraries are API's - things that I2P has that allow its application layer to work

**Comment by luciewho** [comment]
thank you! that helps

**Comment by luciewho** [comment]
Wanted to make a note of the personas. We have recently been working on and talking about the Technical Documentation and the "regular" (there may be a better word?) Documentation for developers. There seem to be at least two types of developers, those that work with the network, those that work with applications and APIs, those that work on...something else that don't require technical documentation? 

<img width="778" alt="Screen Shot 2021-09-02 at 5 07 06 PM" src="https://user-images.githubusercontent.com/6728799/131931155-e76fa319-6f04-4b2d-808b-c8924791fa88.png">

**Comment by Shoalsteed** [comment]
Here are some I think of:

new users of the software
people who are interested in and familiar with privacy tools
people who are system admin types who will contribute to the network
people who write code
people who make apps
people who are doing research

**Comment by luciewho** [comment]
**researchers and other tools**
https://calyxos.org/docs/about/team/
https://www.robertwgehl.org
https://usable.tools (Ashley Fowler from Internews)
https://usable.tools/personas/
http://web.cs.ucla.edu/security/
http://web.cs.ucla.edu/~rafail/
https://tech.cornell.edu/research/security-privacy/
https://homes.cs.washington.edu/~supersat/index.html

**journalists**
reporters without borders
https://helpdesk.rsf.org/digital-security-guide/anonymity/what-anonymisation-means-and-what-it-doesnt-mean/
https://gijn.org/series/my-favorite-tools/
https://gijn.org/2020/12/15/my-favorite-tools-2020-top-investigative-journalists-tell-us-what-theyre-using/

**Comment by Shoalsteed** [comment]
Closing this since we are using discussions in the Usability Lab to discuss research.
