### ISSUE TITLE
Copy

### ISSUE THREAD

**Issue by Shoalsteed** [Shoalsteed/UX#25]
updating copy for download & Install process

**Comment by Shoalsteed** [comment]
The I2P Software ( learn More)
https://geti2p.net/en/about/software


The I2P software includes everything you need to connect to the I2P network, as well as applications and configuration options for communicating and setting up your own services. Send mail, use the I2P bitorrent client, connect to irc, or create your own site or forum!

The I2P software includes:
**A router & router console**: The I2P router will connect you to the network. This is similar to how a home router works. The router console provides access to your connection stats, router connection health, as well as a stop and start option. It includes a light and dark theme, and provides news about updates and quick access to your applications and settings.

**SusiMail**: SusiMail is a secure email client. It is primarily intended for use with Postman’s email servers inside of the I2P network . It is designed to avoid leaking information about email use to other networks. SusiMail is bridged so it can send and receive email from the internet as well. Occasionally you may see some services like Gmail classifying it as spam, which you can correct in your Internet email service providers settings.

**I2PSnark**: Snark is an I2P network only BitTorrent client. It never makes a connection to a peer over any other network.

The Address Book: This is a locally-defined list of human-readable addresses ( ie: i2p-projekt.i2p) and corresponding I2P addresses.(udhdrtrcetjm5sxzskjyr5ztpeszydbh4dpl3pl4utgqqw2v4jna.b32.i2p) It integrates with other applications to allow you to use those human-readable addresses in place of those I2P addresses. It is more similar to a hosts file or a contact list than a network database or a DNS service. There is no recognized global namespace, you decide what any given .i2p domain maps too in the end.

**The QR Code Generator**: Besides the Address Book, I2P addresses can be shared by converting them into QR codes and scanning them with a camera. This is especially useful for Android devices.

**I2P Web Server**:This is your own anonymous I2P webserver. Simply edit the files in the webserver's root directory and your site will be public once you follow the instructions included.

**I2P Hidden Services Manager** This is a general-purpose adapter for forwarding services ( ie SSH ) into I2P and proxying client requests to and from I2P. It provides a variety of “Tunnel Types” which are able to do advance filtering of traffic before it reaches I2P.

Should we include screenshots or illustrated screenshots or illustrations ( ie an envelope for mail?)

**Comment by luciewho** [comment]
**To-do for Copy**

Landing page:
new CTA ("Get Started" "Install I2P")
new secondary CTA ("Learn More" "What is I2P?")

New pages:
Getting started page intro paragraph and cards/steps
Learn More page - i2p software and network
 
Download page:
Steps 1-2-3 cards
Clearer description on mirror pages

Installation guide page:
Instructional steps for each OS
 
Config page:
Instructional steps for each browser

**Comment by Shoalsteed** [comment]
**Java Instructions that can be used for all OS options except Debian, Ubuntu and Android**

_Install Java_: I2P is written in Java and requires that Java be installed to run. In addition to the I2P download, you need to install Java if you do not have it already installed. I2P requires Java Runtime Version 7 or higher. (Oracle, OpenJDK, or IcedTea Java Version 7 or 8 recommended, except Raspberry Pi: OpenJDK 9 for ARM, PowerPC: IBM Java SE 7 or 8)
Determine your installed Java version here or type java -version at your command prompt. Only two platforms do not require Java to be installed before I2P is installed, those platforms are Android and Debian and Ubuntu.

**Comment by Shoalsteed** [comment]
**Install I2P**: Once you have Java installed, you can install the I2P software. This is a 2 step process that includes the actual install process as well as a set up wizard.

**Comment by Shoalsteed** [comment]
**Browser Configuration**
Your web browser will need to be configured in order to browse web sites on I2P and to utilize the outproxies available within I2P. Walkthroughs are available for most browsers.

**Comment by Shoalsteed** [comment]
**CTA**
_The Invisible Internet is a privacy by design, people-powered network. It is a truly free and anonymizing Internet alternative._

New Option:
An anonymizing peer to peer internet alternative

**Comment by Shoalsteed** [comment]
**Getting Started with I2P**

The Invisible Internet Project (I2P) is a fully encrypted private network layer. The network protects your activity and
location. Additionally, I2P has created transport protocols that resist DPI censorship. 

I2P is a peer-to-peer network. Peers make a portion of their resources, particularly bandwidth, available
to other network participants. This allows the network to function with relying on centralized servers.

I2P has an application layer with easy to use APIs for creating your own privacy - aware apps.


Basic Steps
1 Download
I2P needs Java to run for Windows, Mac,
and Linux. Download Java here.

2 Installation
Step-by-step installation guides include
setting up Java, installing I2P and using the
I2P set-up wizard.

3 Configuration
Configure your browser settings to be
compatible with the I2P network.
Download I2P Install Configure

**Comment by luciewho** [comment]
> **Java Instructions that can be used for all OS options except Debian, Ubuntu and Android**
> 
> _Install Java_: I2P is written in Java and requires that Java be installed to run. In addition to the I2P download, you need to install Java if you do not have it already installed. I2P requires Java Runtime Version 7 or higher. (Oracle, OpenJDK, or IcedTea Java Version 7 or 8 recommended, except Raspberry Pi: OpenJDK 9 for ARM, PowerPC: IBM Java SE 7 or 8)
> Determine your installed Java version here or type java -version at your command prompt. Only three platforms do not require Java to be installed before I2P is installed, those platforms are Android and Debian and Ubuntu.

The last sentence says "two platforms" but mentions Android, Debian, and Ubuntu. Is that 3 then? Or do Debian and Ubuntu go together under Linux?

**Comment by luciewho** [comment]
> **Getting Started with I2P**
> 
> The Invisible Internet Project (I2P) is a fully encrypted private network layer. The network protects your activity and
> location. Additionally, I2P has created transport protocols that resist DPI censorship.
> 
> I2P is a peer-to-peer network. Peers make a portion of their resources, particularly bandwidth, available
> to other network participants. This allows the network to function with relying on centralized servers.
> 
> I2P has an application layer with easy to use APIs for creating your own privacy - aware apps.
> 
> Basic Steps
> 1 Download
> I2P needs Java to run for Windows, Mac,
> and Linux. Download Java here.
> 
> 2 Installation
> Step-by-step installation guides include
> setting up Java, installing I2P and using the
> I2P set-up wizard.
> 
> 3 Configuration
> Configure your browser settings to be
> compatible with the I2P network.
> Download I2P Install Configure

For Step 1, I think it needs to have something in there about downloading I2P rather than just Java, because the Getting Started page is meant as an overview for all OS types.

The boxes look like this as well, so there's room for more copy. But if there isn't that much copy, then the boxes should be smaller.

<img width="474" alt="Screen Shot 2021-08-19 at 7 10 22 AM" src="https://user-images.githubusercontent.com/6728799/130083602-606a492e-c0c0-4a63-8deb-3e045e4306aa.png">

For the intro section above the steps, I tacked on a "Learn more about I2P" link at the end. I also added a System Requirements section that mentions the Java requirement. I could use the copy above for "Install Java" instead?

<img width="464" alt="Screen Shot 2021-08-19 at 7 11 58 AM" src="https://user-images.githubusercontent.com/6728799/130083826-0f25f2a5-35e2-41fc-bac1-be53d0d1405d.png">

**Comment by Shoalsteed** [comment]
> > **Java Instructions that can be used for all OS options except Debian, Ubuntu and Android**
> > _Install Java_: I2P is written in Java and requires that Java be installed to run. In addition to the I2P download, you need to install Java if you do not have it already installed. I2P requires Java Runtime Version 7 or higher. (Oracle, OpenJDK, or IcedTea Java Version 7 or 8 recommended, except Raspberry Pi: OpenJDK 9 for ARM, PowerPC: IBM Java SE 7 or 8)
> > Determine your installed Java version here or type java -version at your command prompt. Only three platforms do not require Java to be installed before I2P is installed, those platforms are Android and Debian and Ubuntu.
> 
> The last sentence says "two platforms" but mentions Android, Debian, and Ubuntu. Is that 3 then? Or do Debian and Ubuntu go together under Linux?

i simply copied an existing typo- three.

**Comment by Shoalsteed** [comment]
regarding tacking on the Learn more about i2p - do we want to interrupt the download and install workflow when this information is going to be available on the landing page?

**Comment by luciewho** [comment]
The basic steps under download page for Mac look like this

<img width="776" alt="Screen Shot 2021-08-19 at 8 46 50 AM" src="https://user-images.githubusercontent.com/6728799/130100314-0bd2b534-6570-477f-bfbe-5ba5c1a0a13d.png">

But the other OS like Android and Docker won't need step 1 (Java). It could have different copy or just remove that card and have only 2 cards.

**Comment by Shoalsteed** [comment]
> The basic steps under download page for Mac look like this
> 
> <img alt="Screen Shot 2021-08-19 at 8 46 50 AM" width="776" src="https://user-images.githubusercontent.com/6728799/130100314-0bd2b534-6570-477f-bfbe-5ba5c1a0a13d.png">
> 
> But the other OS like Android and Docker won't need step 1 (Java). It could have different copy or just remove that card and have only 2 cards.

I think we can add the preamble ie:
_I2P is available in the official repositories for Ubuntu Bionic and later, and Debian Buster and Sid. However, Debian Buster and Ubuntu Bionic (LTS) distributions will have older I2P versions. If you are not running Debian Sid or the latest Ubuntu release, use our Debian repo or Launchpad PPA to ensure you're running the latest I2P version._ where the java box would go.

**Comment by luciewho** [comment]
> regarding tacking on the Learn more about i2p - do we want to interrupt the download and install workflow when this information is going to be available on the landing page?

I would think most users would click it as a new tab or use the back button to return to the getting started page. I figured it would be good to have a way to read more as they scan that page. But I think not interrupting the flow and moving them along to download makes sense too. 

I can try to test it in a usability test and see what users prefer.

**Comment by luciewho** [comment]
> > The basic steps under download page for Mac look like this
> > <img alt="Screen Shot 2021-08-19 at 8 46 50 AM" width="776" src="https://user-images.githubusercontent.com/6728799/130100314-0bd2b534-6570-477f-bfbe-5ba5c1a0a13d.png">
> > But the other OS like Android and Docker won't need step 1 (Java). It could have different copy or just remove that card and have only 2 cards.
> 
> I think we can add the preamble ie:
> _I2P is available in the official repositories for Ubuntu Bionic and later, and Debian Buster and Sid. However, Debian Buster and Ubuntu Bionic (LTS) distributions will have older I2P versions. If you are not running Debian Sid or the latest Ubuntu release, use our Debian repo or Launchpad PPA to ensure you're running the latest I2P version._ where the java box would go.

Sounds good. The copy might need to be cut down to fit into that box. Or the boxes/basic steps can have a slightly different look for Android/Linux. I'll work on that when I make wireframes for other OS.

**Comment by luciewho** [comment]
I highlighted the copy that needs to be looked over in red.

Taglines on the Tech Docs
Copy for the single pages in Tech Docs. Attached is the Overview batch of pages. 

<img width="764" alt="Screen Shot 2021-09-08 at 2 10 42 PM" src="https://user-images.githubusercontent.com/6728799/132586081-9d836651-ad30-4854-9376-06d057606d55.png">

[Docs - Overview.pdf](https://github.com/Shoalsteed/UX/files/7131813/Docs.-.Overview.pdf)

**Comment by luciewho** [comment]
I want to talk about the hierarchy and titling of the pages. There is some inconsistency in how the pages are presented, which I think will affect the copy and how it will be organized.

The page title is at the top right on the main menu (should be moved to inside the actual page itself since the new main menu links will be there). 

Some of the section headers are centered like this:

<img width="1194" alt="Screen Shot 2021-09-08 at 2 29 35 PM" src="https://user-images.githubusercontent.com/6728799/132588182-c7f74bca-f7d1-427e-a28d-3b08ee585789.png">

Centered section headers with sub-headers left aligned with a line underneath:
<img width="791" alt="Screen Shot 2021-09-08 at 2 31 02 PM" src="https://user-images.githubusercontent.com/6728799/132588368-77129b9c-353e-4aa2-a73d-785cb1374622.png">

On other pages, the section header is left aligned with a line and sub-headers left aligned no line:
<img width="796" alt="Screen Shot 2021-09-08 at 2 32 12 PM" src="https://user-images.githubusercontent.com/6728799/132588475-56c8c982-4e57-4f8c-8c3f-37963de6483e.png">

**Comment by Shoalsteed** [comment]
i wonder if this is just a css fix?

**Comment by luciewho** [comment]
Yeah I think it will just involve CSS. 

I think all the headers should be left-aligned along with the Page Title. There can be a different color or font for the page title for distinction. And keeping the line under the header helps provide more organizational clarity and distinguishes it from the sub-header.

**Comment by luciewho** [comment]
Example of page hierarchy 

![Screen Shot 2021-09-09 at 12 32 39 PM](https://user-images.githubusercontent.com/6728799/132750914-612aa79a-b1e4-4409-9004-2d420e701f83.png)

**Comment by Shoalsteed** [comment]
_Research Section Copy (Taglines)_

**Academic Research**
_General safety guidelines for research ethics and testing the network_


**Academic Papers and Peer Review** 
_Known published papers written about the I2P network_

**Open research topics**
 _A list of open questions for research_

**I2P Metrics** 
 _I2P Metrics collects and analyzes historical infrastructure data from the I2P network_

**Vulnerability Response** 
_Contact, response and disclosure  process_

**Comment by Shoalsteed** [comment]
**App Development Overview and Guide**
_Start writing I2P Specific Applications_ 

**Other Router Topics**
_Software updates, reseeds, GeoIP and configuration file specifications._

**Comment by luciewho** [comment]
Awesome, got all the taglines into Docs!

**Comment by luciewho** [comment]
@Shoalsteed Do you have a recommendation for how the copy for Tool Tip could be revised? 

![Screen Shot 2021-09-25 at 11 20 44 AM](https://user-images.githubusercontent.com/6728799/134782371-f8716950-01bc-460f-ab6d-9f35ae3d8838.png)

**Comment by luciewho** [comment]
Red text - some other way of explaining this more eloquently?

![Screen Shot 2021-09-26 at 12 06 23 PM](https://user-images.githubusercontent.com/6728799/134820897-5661d696-a453-46d8-b113-c3f99634559e.png)

**Comment by luciewho** [comment]
![Screen Shot 2021-10-11 at 5 58 40 PM](https://user-images.githubusercontent.com/6728799/136872872-54fde522-5712-480f-aae7-726add0c6dbd.png)

**Comment by Shoalsteed** [comment]
Regarding Ubuntu - lets get IDK to sort that out.

**Comment by Shoalsteed** [comment]
LS2
#ls2 meetings, Mondays 6:30 PM UTC, IRC #ls2
For development conversations about I2P network performance and security.
Past Topics http://i2pforum.net/viewforum.php?f=13&sid=993d32890ddbe5b00ab242c386d4a78f
I2P Proposals https://geti2p.net/spec/proposals

**Comment by Shoalsteed** [comment]
I2P Developer Meetings
Project meetings are held on the first Tuesday of every month at 8 PM UTC.
If you have something to discuss, please find the developers on IRC in #i2p-dev
The current roadmap can be viewed here https://geti2p.net/en/get-involved/roadmap

**Comment by Shoalsteed** [comment]
I2P Usability Lab
The I2P Usability Lab will announce monthly Discord meetups.
Join us for conversations about our research, and open panel talks with the community.

**Comment by Shoalsteed** [comment]
> @Shoalsteed Do you have a recommendation for how the copy for Tool Tip could be revised?
> 
> ![Screen Shot 2021-09-25 at 11 20 44 AM](https://user-images.githubusercontent.com/6728799/134782371-f8716950-01bc-460f-ab6d-9f35ae3d8838.png)

"Firefox will provide a Proceed with caution warning when accessing and changing configuration options. You will need to choose Accept the Risk and Continue"

**Comment by luciewho** [comment]
Here's what is looks like with the new copy on the Events page. 

I'm not sure about where to put the hashtags #ls2? Does this look right?
Is there a unique description to use for the I2P Developer Meeting? I just copied what was written for LS2.
For I2P Usability Lab, there isn't a time/day set quite yet, so just link to the Discord? Is "Join Meeting on IRC" okay for LS2 and Developer meetings?

<img width="563" alt="Screen Shot 2021-10-15 at 12 15 12 PM" src="https://user-images.githubusercontent.com/6728799/137540860-2d51a01e-e227-4f31-b8ae-f331c703182f.png">

**Comment by Shoalsteed** [comment]
I2P Developer Meetings
Monthly community meetings and updates from developers on current roadmap status.
Project meetings are held on the first Tuesday of every month at 8 PM UTC.
If you have something to discuss, please find the developers on IRC in #i2p-dev
The current roadmap can be viewed here https://geti2p.net/en/get-involved/roadmap

**Comment by luciewho** [comment]
Is there a link for this IRC? "please find the developers on IRC in #i2p-dev "
And links for the "Join Meeting on IRC" and "Join the Discord"

**Comment by Shoalsteed** [comment]
![Screen Shot 2021-10-15 at 3 19 33 PM](https://user-images.githubusercontent.com/50714166/137541373-5864961e-7fd1-4493-af67-54627a3db993.png)

I would make the invite look like this - and where you have Join the meeting , put the irc direction there ( #i2p-dev or Ls2 )

**Comment by Shoalsteed** [comment]
> Is there a link for this IRC? "please find the developers on IRC in #i2p-dev " And links for the "Join Meeting on IRC" and "Join the Discord"

No links, as far as I know! Can confirm with IDK if creating a link is possible for irc.

**Comment by luciewho** [comment]
Oo I see. I'm not familiar with IRC. I'll make a note to ask idk, thanks!

**Comment by luciewho** [comment]
How the page looks currently (URLs for the links in purple text are noted on the side of the wireframe - not seen)

<img width="678" alt="Screen Shot 2021-10-15 at 12 33 20 PM" src="https://user-images.githubusercontent.com/6728799/137543748-8b563731-5dff-425e-a8d2-b278d4204107.png">

**Comment by luciewho** [comment]
Need copy for the tagline for the Presentations, Tutorials, Articles card (text in pink) in the Research page

<img width="804" alt="Screen Shot 2021-11-06 at 9 37 31 PM" src="https://user-images.githubusercontent.com/6728799/140632447-54c1a588-680e-4653-8bcf-ecbf5d09f272.png">

<img width="224" alt="Screen Shot 2021-11-06 at 9 37 39 PM" src="https://user-images.githubusercontent.com/6728799/140632449-4af4e981-7e41-4ac0-9761-acf0e8b3a353.png">

**Comment by luciewho** [comment]
Revise this copy (in pink)? Something I wrote on the spot. Not sure what to call it but I wrote "Old Download Page" as a placeholder. Non-jpackage download process.

<img width="740" alt="Screen Shot 2021-11-06 at 9 39 46 PM" src="https://user-images.githubusercontent.com/6728799/140632476-4429376e-a51a-4f85-a120-0d88789ce767.png">

<img width="329" alt="Screen Shot 2021-11-06 at 9 40 03 PM" src="https://user-images.githubusercontent.com/6728799/140632478-4b28c04b-d1d0-438a-8bae-9de98bc57717.png">

**Comment by Shoalsteed** [comment]
> Need copy for the tagline for the Presentations, Tutorials, Articles card (text in pink) in the Research page
> 
> <img alt="Screen Shot 2021-11-06 at 9 37 31 PM" width="804" src="https://user-images.githubusercontent.com/6728799/140632447-54c1a588-680e-4653-8bcf-ecbf5d09f272.png">
> 
> <img alt="Screen Shot 2021-11-06 at 9 37 39 PM" width="224" src="https://user-images.githubusercontent.com/6728799/140632449-4af4e981-7e41-4ac0-9761-acf0e8b3a353.png">

Maybe we should rename this "Additional Resources"
Copy:
Articles and Presentations about the I2P network

**remove Tutorials since that is software specific

**Comment by Shoalsteed** [comment]
> Revise this copy (in pink)? Something I wrote on the spot. Not sure what to call it but I wrote "Old Download Page" as a placeholder. Non-jpackage download process.
> 
> <img alt="Screen Shot 2021-11-06 at 9 39 46 PM" width="740" src="https://user-images.githubusercontent.com/6728799/140632476-4429376e-a51a-4f85-a120-0d88789ce767.png">
> 
> <img alt="Screen Shot 2021-11-06 at 9 40 03 PM" width="329" src="https://user-images.githubusercontent.com/6728799/140632478-4b28c04b-d1d0-438a-8bae-9de98bc57717.png">

I2P Java developers 
For people who are Java developers, we suggest downloading the full Java software. *** ask Idk about wording here

**Comment by luciewho** [comment]
Finesse the copy in pink. 

<img width="956" alt="Screen Shot 2021-11-21 at 11 03 29 AM" src="https://user-images.githubusercontent.com/6728799/142775487-8d54e308-e882-4d1d-a72c-64d80e29d9c3.png">

**Comment by luciewho** [comment]
Revise the copy in the hero image to be more like everyday language, cut down the jargon even more or entirely. Example of new copy in second image.

<img width="329" alt="Screen Shot 2021-11-21 at 11 04 07 AM" src="https://user-images.githubusercontent.com/6728799/142775510-1a33ef25-30b6-4526-94f0-d96c09cad7c5.png">

<img width="335" alt="Screen Shot 2021-11-21 at 11 04 19 AM" src="https://user-images.githubusercontent.com/6728799/142775521-466747ab-4380-418b-b0e1-cdc34ec9d495.png">


We are building a private and anonymizing network.
A place to gather, create and explore without giving up your data and identity.??

**Comment by luciewho** [comment]
New tagline for Tutorials

<img width="256" alt="Screen Shot 2021-11-22 at 10 06 01 AM" src="https://user-images.githubusercontent.com/6728799/142912680-945afb7b-43f5-4207-80a0-f14a979e203c.png">

Guides For Developer, Service Operators and Admins??

**Comment by luciewho** [comment]
Let's put these in order of priority.
Copy revision pages: translation, reseed, intro, tech intro, glossary, get involved, software licenses, dev guidelines, roadmap, FAQ reorg, donate, contact

1. Intro
2. Tech Intro
3. FAQ (may tie into pages that need to be created)
4. Glossary
5. Get Involved
6. Translation
7. Software Licenses
8. Dev Guidelines
9. Donate 
10. Contact
11. Roadmap (based on idk)

**Comment by luciewho** [comment]
[Intro.pdf](https://github.com/Shoalsteed/UX/files/7583561/Intro.pdf)

**Comment by Shoalsteed** [comment]
> Finesse the copy in pink.
> 
> <img alt="Screen Shot 2021-11-21 at 11 03 29 AM" width="956" src="https://user-images.githubusercontent.com/6728799/142775487-8d54e308-e882-4d1d-a72c-64d80e29d9c3.png">

https://github.com/Shoalsteed/I2P-Secure-Design-Collective/issues/86

https://www.gnu.org/philosophy/free-sw.html

**Comment by luciewho** [comment]
https://geti2p.net/en/get-involved/guides/dev-guidelines

Report Bugs needs to be changed to Issues. Copy in the paragraphs updated.

"trac needs to be replaced with Git issues, go through and make sure that any new or missing ways for how to contribute using Git is available and updated."

**Comment by Shoalsteed** [comment]
> https://geti2p.net/en/get-involved/guides/dev-guidelines
> 
> Report Bugs needs to be changed to Issues. Copy in the paragraphs updated.
> 
> "trac needs to be replaced with Git issues, go through and make sure that any new or missing ways for how to contribute using Git is available and updated."

https://github.com/Shoalsteed/UX/issues/59 updated
