### ISSUE TITLE
Visuals/ Graphics

### ISSUE THREAD

**Issue by Shoalsteed** [Shoalsteed/UX#26]

**Comment by Shoalsteed** [comment]
![i2p poster](https://user-images.githubusercontent.com/50714166/130510930-1bae1522-74cd-4c0c-a76d-5e406c1084e1.png)

Idea for download page - a poster

**Comment by luciewho** [comment]
https://lucid.pixsellz.io/?ref=uistore.design
https://thenounproject.com

**Comment by Shoalsteed** [comment]
![elements](https://user-images.githubusercontent.com/50714166/130512213-0621c3a2-3126-4a64-a57c-fd5bfeca2b8d.png)

ideas for icon/elements style - free!

**Comment by luciewho** [comment]
![Screen Shot 2021-08-23 at 1 23 45 PM](https://user-images.githubusercontent.com/6728799/130514315-a01d6f24-72d7-4df1-99fc-3ee3a8b73975.png)

Thinking it would be nice to have something like for the product pitch section. Screenshot of the I2P email, screenshot of torrenting going on, screenshot of code snippet

**Comment by Shoalsteed** [comment]
![1](https://user-images.githubusercontent.com/50714166/130652113-873d6d14-556a-4bc9-b04d-a39dfe7857ae.png)
![2](https://user-images.githubusercontent.com/50714166/130652117-1eb888ac-5592-46f0-95da-a49dae536874.png)

free - stars & and also "tunnels" / things that can be used to illustrate the network

**Comment by luciewho** [comment]
looks cool!

**Comment by Shoalsteed** [comment]
![1](https://user-images.githubusercontent.com/50714166/130868615-3f423717-bb0d-45b5-825c-0d38e73c51d0.png)
![3](https://user-images.githubusercontent.com/50714166/130868618-780f6bda-3220-464c-8cde-882335e85987.png)
![4](https://user-images.githubusercontent.com/50714166/130868619-1a898929-1f70-407d-a997-bf55656ead76.png)
![5](https://user-images.githubusercontent.com/50714166/130868620-c3a395ea-aee0-48bf-8b53-d18294369939.png)
![6](https://user-images.githubusercontent.com/50714166/130868622-0683498a-ad64-4625-9116-4a2cfaf728d1.png)
![7](https://user-images.githubusercontent.com/50714166/130868623-a350d0ed-76e0-4e63-841f-c2ba94225736.png)

**Comment by Shoalsteed** [comment]
![Untitled design (5)](https://user-images.githubusercontent.com/50714166/131360073-4c81f88d-c67c-4825-8761-63636450ff11.png)
![Untitled design (6)](https://user-images.githubusercontent.com/50714166/131360075-b89d4b54-322b-4e23-9ff7-ed50021fc1f6.png)

**Comment by Shoalsteed** [comment]
[Untitled design (9).zip](https://github.com/Shoalsteed/UX/files/7079522/Untitled.design.9.zip)

new mac install screenshots

**Comment by Shoalsteed** [comment]
[Untitled design (10).zip](https://github.com/Shoalsteed/UX/files/7079737/Untitled.design.10.zip)

updated - no numbers

**Comment by Shoalsteed** [comment]
![abstract-267046_1920](https://user-images.githubusercontent.com/50714166/132569266-f2f1ac7d-3baa-4d2a-9810-ddc5ed2cb74e.png)
![abstract-1780370_1920](https://user-images.githubusercontent.com/50714166/132569269-384f95f3-3473-4c8b-bf13-ac7dd283a1a0.png)
![background-1939128_1280](https://user-images.githubusercontent.com/50714166/132569294-72be75f7-e759-4288-9f00-9a853174a770.jpg)
![network-4760284_1920](https://user-images.githubusercontent.com/50714166/132569505-aff6c812-92e1-4d92-bc1b-e52c8026236c.png)
![rotation-2721735_1920](https://user-images.githubusercontent.com/50714166/132569507-97fa1974-55c8-431f-827f-5afae69ca344.jpg)

**Comment by Shoalsteed** [comment]
![guilloche-1520728_1280](https://user-images.githubusercontent.com/50714166/132569579-f590b3dd-cda0-45f4-af1b-7ec74ae30b94.png)
![monochrome-2484055_1920](https://user-images.githubusercontent.com/50714166/132569585-cf12c36c-5228-4755-910b-9ec79a94147d.jpg)

**Comment by Shoalsteed** [comment]
[Add a subheading.zip](https://github.com/Shoalsteed/UX/files/7131361/Add.a.subheading.zip)
ideas for layout/ use case for some of the graphics above

**Comment by luciewho** [comment]
New versions

I think one thing that would be useful is to have sample copy to work with when designing specific sections on the landing page. I put in some stuff from the graphics and parity's website or stuff I made up in red.

[Landing Page 1920px.pdf](https://github.com/Shoalsteed/UX/files/7132584/Landing.Page.1920px.pdf)

I'm leaning towards version 6a or 6b (no line). v7's banner background is too tech-y looking and v8 is too dark.

I used more white space in v6a and v6b and I think it feels less cramped too.

**Comment by Shoalsteed** [comment]
[assets.zip](https://github.com/Shoalsteed/UX/files/7198189/assets.zip)

here are some different ideas for assets. all free and customizable.

**Comment by luciewho** [comment]
https://www.are.na/superhi/open-source-illos
https://www.figma.com/community/file/860753592237372239
https://icons8.com/illustrations/style--abstract

**Comment by Shoalsteed** [comment]
![1](https://user-images.githubusercontent.com/50714166/140969484-a989222c-a4ce-4843-82dd-be52b6a02ec7.png)
![2](https://user-images.githubusercontent.com/50714166/140969487-98793523-169a-4ddc-adab-b07345ccc4f7.png)
![3](https://user-images.githubusercontent.com/50714166/140969488-01a7ab2f-e85a-43a7-8091-43a000d2dbad.png)
![4](https://user-images.githubusercontent.com/50714166/140969489-78ab6331-b06d-470b-b9ec-d402454afcf8.png)
![5](https://user-images.githubusercontent.com/50714166/140969490-b19e6508-2b68-4bdd-873b-2adc3e723959.png)
