### ISSUE TITLE
Docs

### ISSUE THREAD

**Issue by luciewho** [Shoalsteed/UX#28]
https://geti2p.net/en/docs

[Docs.pdf](https://github.com/Shoalsteed/UX/files/7050417/Docs.pdf)

**Comment by Shoalsteed** [comment]
We should add a research section as well probably and move the Papers to it

**Comment by luciewho** [comment]
Research section of Docs

![Screen Shot 2021-08-27 at 1 38 27 PM](https://user-images.githubusercontent.com/6728799/131186010-d49fb421-d1ea-47cb-8fc8-53ebcdefaaab.png)

Working off of the IA below: 
![Screen Shot 2021-08-27 at 1 37 15 PM](https://user-images.githubusercontent.com/6728799/131186019-9fa68253-b3fe-4b76-b483-7f5ae92a1430.png)

![Screen Shot 2021-08-27 at 1 37 00 PM](https://user-images.githubusercontent.com/6728799/131186306-9b894706-8ec8-4997-801b-35656c107364.png)


Should I disregard what is currently on the main menu (Impressum, Vulnerability Response Process)?
Is "Papers on I2P" and "Academic Papers and Peer Reviews" the same?
Is "Presentations, Tutorials, Articles, and Interviews" and "Talks" the same?
The "Academic Research" page (https://geti2p.net/en/research) seemed important, but isn't on canva IA. Seems like an intro to research? Do we need anything on this page?

**Comment by Shoalsteed** [comment]
The Vulnerability Process - that one I am not sure where it should go. I think it applies best to the research.
I think I ran out of steam when I was making that canva chart....
Papers on I2P can go  - it is the same as academic papers
The academic papers are different than the content in the presentations section. The presentation section actually has some dead links too I think...

**Comment by luciewho** [comment]
Put together most of the pages for Docs

[Docs.pdf](https://github.com/Shoalsteed/UX/files/7069722/Docs.pdf)

Some questions/comments that came up for me:

On canva IA:
Router Message Protocol is under Network (is under wildcard Router category on wireframe, long with Other Router Topics)
Network Database is under Cryptography (is under Network on wireframe. Maybe Cryptography category since it has pages on cryptography?)

“The lowest-level API used for clients (applications) to send and receive traffic to a router.” “Distributed storage and retrieval of information about routers and clients.” Add as tagline on cards? Cut down the ones that are over two lines long.

Double-checking that “Application Layer API and Protocols” is the section for the API section with screenshots? Only one page (BOB) has potential screenshots. Do “End-to-End Transport API and Protocols” and “Client-to-Router Interface API and Protocol” need screenshots as well? They are currently cards under Application.

Some pages under “Application Layer API and Protocols” have no links. What to do for wireframe? Grayed-out card?

Canva has a “Meet Your Maintainers/Get Involved” category. Should this replace the “Research” category at the top and allow Research its own category as a card?

**Comment by Shoalsteed** [comment]
Let's hand sort this together on Monday. It has been a while since I looked at this and I have probably missed some things or sorted into non-optimal categories! I need IDK to have a look too once we get this in order.

**Comment by Shoalsteed** [comment]
**I2P Application Layer** 
![Screen Shot 2021-08-31 at 4 07 13 PM](https://user-images.githubusercontent.com/50714166/131568969-620b3b07-4175-45be-a09f-a056651aec03.png)


Application Development Overview and Guide
Naming and Address Book
Address Book Subscription Feed Commands
Plugins Overview
Plugin Specification
Managed Clients
Embedding the router in your application
Bittorrent over I2P
I2PControl Plugin API
hostsdb.blockfile Format
Configuration File Format

**Application Layer API and Protocols**
_High-level, easy-to-use APIs for applications written in any language to send and receive data._

![Screen Shot 2021-08-31 at 4 09 58 PM](https://user-images.githubusercontent.com/50714166/131569199-4ddd983e-9f41-4a13-b43a-75cdad32d693.png)


I2PTunnel
I2PTunnel Configuration
SOCKS Proxy
HTTP Proxy ***
CONNECT Proxy ***
IRC Proxy ***
SOCKS IRC Proxy ***
Streamr Proxy ***
HTTP Bidir Proxy ***
SAM Protocol
SAMv2 Protocol
SAMv3 Protocol
BOB Protocol
   *** - deadlink

**End-to-End Transport API and Protocols**
_The end-to-end protocols used by clients for reliable and unreliable communication._

![Screen Shot 2021-08-31 at 4 11 26 PM](https://user-images.githubusercontent.com/50714166/131569376-b43dd66c-06a0-4f5c-b01c-0a9f7f6fd419.png)

Streaming Library
Streaming Protocol Specification
Streaming Javadoc
Datagrams
Datagram Javadoc

**Client-to-Router Interface API and Protocol**
_The lowest-level API used for clients (applications) to send and receive traffic to a router. Traditionally used only by Java applications and higher-level APIs._

![Screen Shot 2021-08-31 at 4 12 46 PM](https://user-images.githubusercontent.com/50714166/131569531-4154d3ed-1bae-4a56-988d-0603bd651afa.png)

I2CP - I2P Control Protocol / API overview
I2CP Specification
I2CP API Javadoc
Common data structures specification
Data Structures Javadoc

**Comment by Shoalsteed** [comment]
**I2P Network Technical Documentation** 
Technical Introduction ***** should the copy about old apps be moved to Application section???
Threat model and analysis
Comparisons to other anonymous networks
Specifications
Protocol stack chart

**Comment by Shoalsteed** [comment]
**Router Message Protocol**
_I2P is a message-oriented router. The messages sent between routers are defined by the I2NP protocol._

I2NP - I2P Network Protocol Overview
I2NP Specification
I2NP Javadoc
Common data structures specification
Encrypted Leaseset specification
Data Structures Javadoc

**Other Router Topics**
Naming and addressbook
Strict Countries?? ( should this go in software privacy guide??)
Router software updates
Router reseed specification
Native BigInteger Library
Time synchronization and NTP
Performance
Configuration File Format
GeoIP File Format

**Comment by Shoalsteed** [comment]
**End-to-End Encryption**
_How client messages are end-to-end encrypted by the router._

ECIES-X25519-AEAD-Ratchet encryption for destinations
ECIES-X25519 encryption for routers
ElGamal/AES+SessionTag encryption
ElGamal and AES cryptography details

**Network Database**
_Distributed storage and retrieval of information about routers and clients._

Network database overview, details, and threat analysis
Cryptographic hashes
Cryptographic signatures
Red25519 signatures
Router reseed specification
Base32 Addresses for Encrypted Leasesets

**Tunnels**
_Selecting peers, requesting tunnels through those peers, and encrypting and routing messages through these tunnels._

Peer profiling and selection
Tunnel routing overview
Garlic routing and "garlic" terminology
Tunnel building and encryption
ElGamal/AES for build request encryption
ElGamal and AES cryptography details
Tunnel building specification (ElGamal)
Tunnel building specification (ECIES-X25519)
Low-level tunnel message specification
Unidirectional Tunnels
Peer Profiling and Selection in the I2P Anonymous Network 2009 paper (pdf), not current but still generally accurate

**Transport Layer**
_The protocols for direct (point-to-point) router to router communication._
Transport layer overview
NTCP TCP-based transport overview and specification
NTCP2 specification
SSU UDP-based transport overview
SSU specification
NTCP transport encryption
SSU transport encryption
Transport Javadoc
NTCP Javadoc
SSU Javadoc

**Comment by Shoalsteed** [comment]
**Developer's Guides and Resources**

**_MOST OF THIS IS ALREADY IN GET INVOLVED_** 
New Developer's Guide ( Get Involved)
New Translator's Guide ( Get Involved)
Monotone Guide ( make note that this is old )
Developer Guidelines ( Get Involved )
Javadocs on the standard internet: Server 1 Note: always verify that javadocs are current by checking the release number.
Javadocs inside I2P: Server 3 Note: always verify that javadocs are current by checking the release number. ???

Embedding the router in your application ( this is already in application layer docs)
How to Set up a Reseed Server ( get involved)
Ports used by I2P ( In Advanced Software guide) ( should it be duplicated eleswear?
Automatic updates to development builds inside I2P ( get involved dev guides)
Updating the wrapper manually ????
User forum ( Contact)
Developer forum inside I2P ( Contact )
Bug tracker ( get Involved)
I2P Source exported to GitHub (get involved)
I2P Source Git Repo inside I2P(get involved)
Source translation at Transifex ( get involved)

**Comment by Shoalsteed** [comment]
**_Roadmap and Proposals_**
Roadmap
Proposals 
To Do List (not current)
Ancient invisiblenet I2P documents (2003)
The ancient I2P mailing list 2004-07 to 2006-10

**Comment by Shoalsteed** [comment]
[The Invisible Internet Project Technical Overview.zip](https://github.com/Shoalsteed/UX/files/7093519/The.Invisible.Internet.Project.Technical.Overview.zip)

add: 
![Screen Shot 2021-09-01 at 2 57 33 PM](https://user-images.githubusercontent.com/50714166/131728402-5e03c18e-e4f6-4024-b8ba-30f47de11f45.png)
Task list? to roadmap section

**Comment by luciewho** [comment]
Updated Docs. A few comments/Qs in the blue circles, reiterated below:

- Should title be changed to "Technical Documentation"
- Two cards do not have taglines
- Two cards share the same tagline
- Some tagline are 3 lines long. It is a bit crowded. A few options here: make purple part bigger for all cards, make font smaller for all cards, cut down 3 lines to 2 
- I shortened Application to App in the first two cards under I2P Application Layer because it was too long
- For Roadmap and Proposals, is Development Roadmaps two separate pages named 1) Development 2) Roadmaps or one page (as it is currently shown). There were no bullet points next to the title so I wasn't sure

[Docs.pdf](https://github.com/Shoalsteed/UX/files/7094427/Docs.pdf)

**Comment by Shoalsteed** [comment]
> Updated Docs. A few comments/Qs in the blue circles, reiterated below:
> 
> * Should title be changed to "Technical Documentation"
Yes

> * Two cards do not have taglines
yup - need to come up with something 

> * Two cards share the same tagline
**End-to-End Transport API and Protocols**

"The end-to-end protocols used by clients for reliable and unreliable communication."

> * Some tagline are 3 lines long. It is a bit crowded. A few options here: make purple part bigger for all cards, make font smaller for all cards, cut down 3 lines to 2
Could we make the card bigger?

> * I shortened Application to App in the first two cards under I2P Application Layer because it was too long
that works

> * For Roadmap and Proposals, is Development Roadmaps two separate pages named 1) Development 2) Roadmaps or one page (as it is currently shown). There were no bullet points next to the title so I wasn't sure
There is only one roadmap, so we can call it Development Roadmap or roadmap 
> 
> [Docs.pdf](https://github.com/Shoalsteed/UX/files/7094427/Docs.pdf)

**Comment by luciewho** [comment]
The Research category that on the previous wireframe, are we moving that from the Tech Docs? Is it going to the Support page?

**Comment by luciewho** [comment]
Bigger cards

[Docs.pdf](https://github.com/Shoalsteed/UX/files/7100588/Docs.pdf)

**Comment by luciewho** [comment]
[Docs.pdf](https://github.com/Shoalsteed/UX/files/7139909/Docs.pdf)

Latest version with skeleton wireframes of each page. The Overview section and some of the other sections have the copy inserted (in red for revision if needed).

**Comment by Shoalsteed** [comment]
<img width="610" alt="Screen Shot 2021-10-13 at 10 34 49 AM" src="https://user-images.githubusercontent.com/50714166/137155147-f993f009-619c-489a-8d91-e4c57444a14f.png">

regarding https://www.figma.com/file/RBaCbkTXWS3FMDGAtHcIjc/Information-Architecture---I2P-Website?node-id=0%3A1 

above is how the research docs are on the site now. Each has a page.

Metrics, Papers , presentations, are there own thing. So a card for each. The docs: research page, open questions and VRP could be one card linking to one page with an index?

**Comment by luciewho** [comment]
Want to make sure. In that case the info architecture will look like this:

<img width="236" alt="Screen Shot 2021-10-13 at 7 46 46 PM" src="https://user-images.githubusercontent.com/6728799/137242121-0a014647-0ce8-4de8-ad1b-7bb08b049928.png">


The cards on the Docs page:
<img width="605" alt="Screen Shot 2021-10-13 at 7 48 07 PM" src="https://user-images.githubusercontent.com/6728799/137242239-cf7fe03d-2b74-4d25-b9e7-be15fe6d896b.png">


When you click on each card, some of the pages would look like this, with a single sub-page:

<img width="763" alt="Screen Shot 2021-10-13 at 7 48 23 PM" src="https://user-images.githubusercontent.com/6728799/137242269-5065f71e-2986-4454-814b-14b827a03ddb.png">

<img width="749" alt="Screen Shot 2021-10-13 at 7 48 31 PM" src="https://user-images.githubusercontent.com/6728799/137242283-d073d829-5987-42d9-87f9-16b3f4a5dd0a.png">

<img width="739" alt="Screen Shot 2021-10-13 at 7 48 44 PM" src="https://user-images.githubusercontent.com/6728799/137242302-aa0ca4e7-21f8-4e04-ae2a-543782b7565f.png">

This is how the rest of the cards on the Docs page are operating, with a bunch of sub-pages nested within each card. But since Research doesn't have all the sub-pages it is a single link. 

Does this make sense and is this okay?

**Comment by Shoalsteed** [comment]
I think it is okay - it makes it easier to navigate visually.
