### ISSUE TITLE
Usability Forum Ideas

### ISSUE THREAD

**Issue by Shoalsteed** [Shoalsteed/UX#30]
Tone: we are building together

-What does security mean to a developer ?
-What does security mean to a user?
-What are the touch points for familiarity with security ?
-What makes you trust ?
-The importance of good design and product development?
-How do we decide what is secure?
-What are the the security/ safe communication tools you use and why ?
-If you do not use a specific all or software, how do you establish trust or safety online? Ask in a way that puts the person answering it in a place of expertise not judgement! ie - It is sometimes makes sense to not use so many tools! Show me your OPSEC!

**Comment by HN-ux** [comment]
The people...

-10 users from East Africa have agreed to participate, ask and answer questions with us
-They are all journalists. All new to I2P
-They've heard about the application tool life-cycle and what is generally needed/involved at each stage
-In March they recorded messages to developers to express some of their needs. Here:
https://github.com/HN-ux/HN-UX/issues/5

**Comment by Shoalsteed** [comment]
we may want to get feedback on the wireframes / portions of them.

**Comment by luciewho** [comment]
**Goal:** 
1) Understand what establishes trust, their concept of privacy and what it means. 
2) Figure out what I2P is missing and what we can do better. How to better position I2P as a valuable tool.


**Questions:**
- What does privacy mean to you? 
- What makes you decide to trust and use a tool?
- What tools are you using for communication (email, messaging, storing files privately)? 
- How much is obscuring where you are and who you are important for you and your sources?
- Do you use your mobile or desktop more? (working from home or working more in the field)
- What are your biggest threats and challenges? How much is phishing or bad actors you have to deal with?


**Workshop idea:** (Helen, maybe you can work this activity into your workshop?)
Privacy vs anonymity — what do people understand as privacy in an application? 
Which are more important to you, which do you understand and don’t understand. Pick and rate. 
1. Encryption
2. IP address is hidden
3. No tracking
4. Anonymity
5. Other

@HN-ux Are we allowed to record the interview? Are we able to screen share during the interview?

**Comment by Shoalsteed** [comment]
**IP address**
A number of a computer or network which is unique and thus can be used to address it. This relates to information about your internet provider and your geographic location. 

**Tracking**
 tracking involves collecting information about your use of or interaction with a web pages. This can mean collection of identifying data like IP , browser, OS, and geographic location. Track can take place in your browser or when using applications on your phone.

**Encryption**
Encryption is the ability to scramble readable text into unreadable text to anyone other than the person who the message is being shared. Some examples of this include using PGP or using a privacy tool that includes encryption so that it cannot see or read your email or messages. 

**Anonymity** 
In the case of how a technology provides anonymity, this would mean the obfuscation of your online activities as well and protection of your IP address. 

**Other**
Another option for privacy and protection of identity may include using a fictitious ( pseudonymous) name or personality on online forums or for an email address.

**Comment by Shoalsteed** [comment]
I think that what we will see from the activity is what of the above is part of the scope of what a person considers privacy and what it means to them and what they need or want to protect ( which will answer questions about person threat model indirectly).
This way we focus on something closer to needs evaluation rather than introducing I2P to much ( yet)

**Comment by luciewho** [comment]
**Workshop Activity**

_Share question and have participants write down their response and discuss. Take notes on what they say._
1. What does privacy and anonymity mean to you?

_Share definitions for each privacy concept. Have participants write down their ranking_
2.  Rank in order of importance to you. 
Encryption 
IP address is hidden (physical location, provider identity who they get internet service from)
No tracking
Anonymity
Pseudonym

_Have participants write down their ranking._
3. Circle and rate each one, 1 being Not Important — 5 being Very Important 
Encryption — 1 2 3 4 5
IP address is hidden — 1 2 3 4 5
No tracking — 1 2 3 4 5
Anonymity — 1 2 3 4 5
Pseudonym — 1 2 3 4 5

_Save all materials and notes from the workshop for research purposes._

**Comment by luciewho** [comment]
These are some research findings from the Forum that stood out to me:

**What makes you decide to trust and use a tool?**
Knowing how the tool is used, its usability, is it easy for people to use
Everyone or many people can use the tool, not limited to a small group. Can share info with others.
Consider feedback mechnism. Is it safe? 
Finding out the source, who built this tool? Is that person credible.
Its efficiency, how does it work? Is it fast, does it back up your info?
"We have to be careful in the selection of tools that we use. Some tools we use alone. We need apps that every uses. What tools are used in Uganda? When developing a tool you need to consider all that."

**What to do to ensure privacy and security?**
Encrypt your messages, for electronic info.
Have different passwords on different accounts.
Do not use free wifi, Internet cafe. There are hackers. 
Avoid click on links and prompts that are phishing scams.
When filling out account, do not put every bit of info about yourself on there.
