### ISSUE TITLE
Reseed 

### ISSUE THREAD

**Issue by Shoalsteed** [Shoalsteed/UX#35]
Include all docs on Reseeds 
https://geti2p.net/en/docs/reseed
https://geti2p.net/en/get-involved/guides/reseed
https://geti2p.net/en/blog/post/2020/06/07/file-based-reseed
https://i2pgit.org/idk/reseed-tools
Add Phong's reseed research here as well. 
https://homepage.np-tokumei.net/post/notes-censorship-resistant-i2p-reseeding/
https://homepage.np-tokumei.net/post/notes-i2p-reseed-over-cloudflare/

**Comment by Shoalsteed** [comment]
All Reseed docs should be accessed from the Reseed page and then display a menu with the links / titles of other pages.

**Comment by eyedeekay** [comment]
https://geti2p.net/en/docs/reseed

**Comment by Shoalsteed** [comment]
Page has been updated, closing issue
