### ISSUE TITLE
Images and Licensing

### ISSUE THREAD

**Issue by luciewho** [Shoalsteed/UX#37]
Download arrow: font library icon collection
Java logo: https://www.svgrepo.com/svg/75601/java-logo
Windows logo:https://www.svgrepo.com/svg/30407/windows
Apple logo: https://www.svgrepo.com/svg/69341/apple-logo
Ubuntu logo: https://design.ubuntu.com/downloads/
Debian logo: https://www.debian.org/logos/
Linux logo: https://www.svgrepo.com/svg/3968/linux
Android logo: https://icons8.com/icons/set/android-logo
Docker logo: https://icons8.com/icons/set/docker-logo
Computer image for Mac
Computer image for Windows
Computer image for Linux
Mobile image for Android

Licenses:
https://www.svgrepo.com/page/licensing 
https://icons8.com/license

**Comment by luciewho** [comment]
Putting a note here about the Android mobile and Mac computer with constellations. 

Constellation images will depend on what the hero image/landing page images will look like. 

Eventually will need transparent background and .svg files of these images.

**Comment by luciewho** [comment]
[Download Images.zip](https://github.com/Shoalsteed/UX/files/7316712/Download.Images.zip)

All the images for the Download OS pages ONLY. (Does not include installation instructions, footer, etc)

**Comment by Shoalsteed** [comment]
[assets (5).zip](https://github.com/Shoalsteed/UX/files/7468213/assets.5.zip)

https://www.canva.com/policies/free-media/

**Comment by luciewho** [comment]
Images that go in the header, logo and two icons

[Header Images.zip](https://github.com/Shoalsteed/UX/files/7604969/Header.Images.zip)

**Comment by luciewho** [comment]
[Landing Page Images.zip](https://github.com/Shoalsteed/UX/files/7777460/Landing.Page.Images.zip)

**Comment by luciewho** [comment]
Footer images (just Itoopie)

[Footer Images.zip](https://github.com/Shoalsteed/UX/files/7830942/Footer.Images.zip)
