### ISSUE TITLE
User Engagement/testing

### ISSUE THREAD

**Issue by HN-ux** [Shoalsteed/UX#4]
**Developer questions**

**Question 1:**
If there existed a tool/application/software that could enable  you to send an anonymous email without revealing sender info, when it was sent or received...would you use it?

![would yo use it](https://user-images.githubusercontent.com/80400452/111623418-467eb600-87e2-11eb-9935-7537cecf12e5.png)

and I would be motivated to use it especially if you...

![Bio data](https://user-images.githubusercontent.com/80400452/111622624-534eda00-87e1-11eb-9698-cbad97438838.png)

**Question 2:**
How important is it to you that those emails would be able to reach receipts who aren't already using secure email channels?

![contacts security](https://user-images.githubusercontent.com/80400452/111622238-d6236500-87e0-11eb-9f6c-18d3049e0ba2.png)

**Question 3**
How large an attachment/file do you normally need to send via email?
Sub question
Is file sharing something that's important to you?
![file sharing](https://user-images.githubusercontent.com/80400452/111526096-37522680-8756-11eb-8211-f300bf6a6621.png)

![file size](https://user-images.githubusercontent.com/80400452/111526163-4b962380-8756-11eb-83f3-ce25e109c306.png)

**Comment by HN-ux** [comment]
**Proposed changes and user testing areas**

Landing page: https://geti2p.net/en/
![image](https://user-images.githubusercontent.com/80400452/113559927-b4ecb200-95f1-11eb-97f5-b0c2bd0b95ab.png)

**Summary**

-Re -write and add graphic to the definitions under: 
what is I2P
I2P Cares About Privacy
Peer-Peer
-Add button for “’FAQs” and ‘’Guides’’, the latter can include how to use I2P for win and mac

**To test on this page**

-What is the users’ first impression? Does the user go through the definitions? Do they go straight to “get I2P”?
-What questions come up about I2P?


**Download page: https://geti2p.net/en/download**

![image](https://user-images.githubusercontent.com/80400452/113560071-f1201280-95f1-11eb-9225-b8d6f48b8095.png)


**Summary**
-Create a ‘’basics steps or what you need’’ infographic with updated info (might leave out the java stuff). The note about Firefox installer recommendation for windows should only appear for windows install page
-Remove the ‘’release notes’’ and reallocate
-Create a button that says download next to a users’ OS so that its very clear and obvious where to click

**To test on this page**
-what OS is the user going for? Do they seem hesitant?
-What does the user expect when they click to download?


**Post install: https://geti2p.net/en/download/0.9.49/clearnet/https/download.i2p2.de/i2pinstall_0.9.49_windows.exe/download**

![image](https://user-images.githubusercontent.com/80400452/113560179-1b71d000-95f2-11eb-817b-3884344d1740.png)


**Summary**
-Organise the information on this page by OS. Create icons/visualisation
1. How to configure browser -2. How to enter the I2P application (including screenshots of desktop shortcuts) etc 
- Add install guides

**To test on this page**
-What are the users’ questions?

**Comment by Shoalsteed** [comment]
![1](https://user-images.githubusercontent.com/50714166/113617907-f34f9480-9624-11eb-8957-074e0f2b5d5b.png)
![2](https://user-images.githubusercontent.com/50714166/113617921-f64a8500-9624-11eb-9a5e-157c2feebc10.png)
![Add a little bit of body text](https://user-images.githubusercontent.com/50714166/113625437-ef287480-962e-11eb-929e-cd23fa8c30d6.png)

**Comment by Shoalsteed** [comment]
![ideas-space](https://user-images.githubusercontent.com/50714166/113620812-d1f0a780-9628-11eb-93c4-eda27451d77c.png)
![monoline](https://user-images.githubusercontent.com/50714166/113621451-a28e6a80-9629-11eb-8d43-ecefe0f3fb5d.png)
![bold](https://user-images.githubusercontent.com/50714166/113621965-58f24f80-962a-11eb-84eb-caf6c398ca3b.png)

**Comment by Shoalsteed** [comment]
looking for suggestions for what to consider for the rewrite for the landing page

**Comment by HN-ux** [comment]
> 
> 
> ![1](https://user-images.githubusercontent.com/50714166/113617907-f34f9480-9624-11eb-8957-074e0f2b5d5b.png)
> ![2](https://user-images.githubusercontent.com/50714166/113617921-f64a8500-9624-11eb-9a5e-157c2feebc10.png)
> ![Add a little bit of body text](https://user-images.githubusercontent.com/50714166/113625437-ef287480-962e-11eb-929e-cd23fa8c30d6.png)

Both are fantastic. The mirror and sig things are really confusing

**Comment by HN-ux** [comment]
> 
> 
> ![ideas-space](https://user-images.githubusercontent.com/50714166/113620812-d1f0a780-9628-11eb-93c4-eda27451d77c.png)
> ![monoline](https://user-images.githubusercontent.com/50714166/113621451-a28e6a80-9629-11eb-8d43-ecefe0f3fb5d.png)
> ![bold](https://user-images.githubusercontent.com/50714166/113621965-58f24f80-962a-11eb-84eb-caf6c398ca3b.png)

Image 1 and image 2 are my favourite

**Comment by Shoalsteed** [comment]
![layout](https://user-images.githubusercontent.com/50714166/113770172-d338d780-96ef-11eb-8478-d235c8c49f59.png)
![Guides](https://user-images.githubusercontent.com/50714166/113770190-d7fd8b80-96ef-11eb-952d-3212d581125f.png)

**Comment by Shoalsteed** [comment]
![Canva - Asteroid Icon](https://user-images.githubusercontent.com/50714166/113778873-e8ffca00-96fa-11eb-9a43-ea0932ba0646.png)
![Canva - Planet Icon (1)](https://user-images.githubusercontent.com/50714166/113779088-2a907500-96fb-11eb-9084-f4014c438c27.png)
![Canva - Planet Icon](https://user-images.githubusercontent.com/50714166/113779510-d5089800-96fb-11eb-9a95-751a6a7ec788.png)

**Comment by Shoalsteed** [comment]
above is the icon set that I am trying out - one I have colourized with i2p purple, the other is as is.

**Comment by Shoalsteed** [comment]
![Guides (1)](https://user-images.githubusercontent.com/50714166/113908467-90850700-97a4-11eb-9a81-8acd7a2d0e78.png)

**Comment by Shoalsteed** [comment]
![3](https://user-images.githubusercontent.com/50714166/113927298-4b200400-97bb-11eb-9e09-2a1172425690.png)
![4](https://user-images.githubusercontent.com/50714166/113927304-4eb38b00-97bb-11eb-9796-8b0003b5726b.png)
![5](https://user-images.githubusercontent.com/50714166/113927313-5115e500-97bb-11eb-9061-18bba64665c7.png)
![6](https://user-images.githubusercontent.com/50714166/113927321-53783f00-97bb-11eb-803b-78d1c357d135.png)
![7](https://user-images.githubusercontent.com/50714166/113927330-56732f80-97bb-11eb-8f22-edf385bb5b33.png)
![8](https://user-images.githubusercontent.com/50714166/113927337-58d58980-97bb-11eb-8ec6-55a37d5cb8db.png)

**Comment by Shoalsteed** [comment]
Re write for the landing page:

**What is I2P**
The Invisible Internet Project (I2P) is a fully encrypted private network layer.
 It protects your activity and location. Ever day people use the network to connect with people without worry of being tracked or their data being collected. In some cases people rely on the network when they need to be discrete and doing sensitive work.

Learn more about connecting to the network! (Link to install guides)?

**I2P Cares About Privacy** 
( leave the same)

**Peer to Peer**
The network is people powered . Peers make a portion of their resources, such as processing power and bandwidth available to other network participants. This allows the network to function with relying on centralized servers. *
**citation https://decentpatterns.xyz/report/#key-terms

**Comment by eyedeekay** [comment]
Made some small edits, text is visible on my test tunnel now.

**Comment by eyedeekay** [comment]
I'm not 100% sure I like the eye one. Got sort of an "Illuminati" thing going on. People get weird about that stuff. Feels like we should steer clear of like, eyes, pyramids, et cetera within reason.

**Comment by Shoalsteed** [comment]
> I'm not 100% sure I like the eye one. Got sort of an "Illuminati" thing going on. People get weird about that stuff. Feels like we should steer clear of like, eyes, pyramids, et cetera within reason.

I think I prefer this one of the 2 https://github.com/Shoalsteed/UX/issues/4#issuecomment-815089332
It is consistent with the space theme. It is not "odd" ie the graphics are straight forward.

**Comment by Shoalsteed** [comment]
![Canva - Asteroid Icon2](https://user-images.githubusercontent.com/50714166/114307392-66d22580-9aad-11eb-8a73-6c7b9846a731.png)
![Canva - Planet Icon 1(1)](https://user-images.githubusercontent.com/50714166/114307399-6e91ca00-9aad-11eb-867d-46b891d6b97e.png)
![Canva - Planet Icon](https://user-images.githubusercontent.com/50714166/114307410-77829b80-9aad-11eb-8156-5f411d7d31b6.png)
![Canva - Rocketship Icon](https://user-images.githubusercontent.com/50714166/114307413-7c474f80-9aad-11eb-975b-d7e61400a09f.png)
![Canva - Satellite Icon](https://user-images.githubusercontent.com/50714166/114307418-8406f400-9aad-11eb-906f-63f77d0582c1.png)
![Canva - Spaceship Icon](https://user-images.githubusercontent.com/50714166/114307424-89fcd500-9aad-11eb-893c-07c0c6709104.png)
![Canva - World Icon](https://user-images.githubusercontent.com/50714166/114307432-91bc7980-9aad-11eb-9b63-aea91bb4836e.png)
