### ISSUE TITLE
JPack Download

### ISSUE THREAD

**Issue by Shoalsteed** [Shoalsteed/UX#44]
add a second download workflow for the new installer to wireframe 
https://eyedeekay.github.io/i2p/osx.html
instructions and some assets live here.

**Comment by Shoalsteed** [comment]
<img width="737" alt="Screen Shot 2021-03-18 at 1 44 26 PM" src="https://user-images.githubusercontent.com/50714166/142280206-e1f1e292-f162-4729-ad50-3eea77b7a20e.png">
<img width="638" alt="Screen Shot 2021-04-02 at 4 41 29 PM" src="https://user-images.githubusercontent.com/50714166/142280837-ab10b8b7-4879-4a83-9d90-94f15cbd5cb1.png">
<img width="371" alt="Screen Shot 2021-04-02 at 4 41 39 PM" src="https://user-images.githubusercontent.com/50714166/142280841-19c48ee8-70e7-49d0-907e-197aaf71d066.png">
<img width="518" alt="Screen Shot 2021-04-02 at 4 41 50 PM" src="https://user-images.githubusercontent.com/50714166/142280844-6856d095-04f2-44bc-86aa-cef70412148b.png">
<img width="233" alt="Screen Shot 2021-04-02 at 4 42 10 PM" src="https://user-images.githubusercontent.com/50714166/142280847-c26da48e-d00a-42d5-ae05-d33e83c87a9e.png">

**Comment by luciewho** [comment]
Add new steps in the Installation Instruction that is text for set up wizard: 1) Set up your language, 2) Bandwidth test, 3) Getting a head start on making your first connections with I2P network (called bootstrapping)

**Comment by luciewho** [comment]
Need text instruction for each screenshot step and maybe green boxes to highlight where to click

**Comment by luciewho** [comment]
New screenshot of first image, it got cut off

**Comment by luciewho** [comment]
Wireframe of Installation Instructions MacOS. Copy in the steps need revision.

[Installation Instructions Mac.pdf](https://github.com/Shoalsteed/UX/files/7610611/Installation.Instructions.Mac.pdf)
