### ISSUE TITLE
IA: Pages that may need work

### ISSUE THREAD

**Issue by Shoalsteed** [Shoalsteed/UX#46]
Developer Resources section

https://geti2p.net/en/get-involved/develop/applications
**_Change Why to How_**
review : this page was last updated in 2013.

https://geti2p.net/en/get-involved/develop/licenses
change to:
_The software developed to support the anonymous communication network I2P is freely available, open source, and user modifiable. To meet these criteria, the project makes use of a variety of legal and software engineering techniques to remove as many barriers to entry as possible for people considering making use of the network , software or contributing to the I2P effort._  ( NEW COPY WRITTEN, WAITING FOR REVIEW AND SITE UPDATE)

https://geti2p.net/en/get-involved/guides/dev-guidelines
trac needs to be replaced with Git issues, go through and make sure that any new or missing ways for how to contribute using Git is available and updated. ( NEW COPY WRITTEN, WAITING FOR REVIEW AND SITE UPDATE)

https://geti2p.net/en/get-involved/roadmap
The format of this needs to be fixed. ( FIXED )

**Comment by Shoalsteed** [comment]
Pages under Introduction

https://geti2p.net/en/about/intro
This page is new and up to date 

comparison pages are fine

https://geti2p.net/en/about/glossary
we need to add definitions of FOSS, and Open Source

**Comment by Shoalsteed** [comment]
All tech docs are probably fine, I need to just go through and catch references to trac , monotone.

**Comment by Shoalsteed** [comment]
Add this to the Glossary https://en.wikipedia.org/wiki/Free_and_open-source_software

**Comment by Shoalsteed** [comment]
Clean up titles and urls for Gitlab instructions
Be consistent with calling it git gitlab

**Comment by Shoalsteed** [comment]
https://geti2p.net/en/docs

<img width="416" alt="Screen Shot 2022-01-05 at 1 26 03 PM" src="https://user-images.githubusercontent.com/50714166/148269171-99331c9d-e548-4b31-acfb-e59409303fa8.png">
http://bobthebuilder.i2p.xyz/mtn/ 

was this slumlord's service?

**Comment by eyedeekay** [comment]
I think so

**Comment by Shoalsteed** [comment]
javadocs urls to ech's site do not work 
https://geti2p.net/en/docs

**Comment by Shoalsteed** [comment]
> I think so

it should be removed if so / does not work

**Comment by Shoalsteed** [comment]
https://geti2p.net/en/docs
<img width="228" alt="Screen Shot 2022-01-05 at 1 31 21 PM" src="https://user-images.githubusercontent.com/50714166/148269845-07273c73-a83b-4991-a727-592f32f5fe93.png">
broken link

**Comment by Shoalsteed** [comment]
<img width="132" alt="Screen Shot 2022-01-05 at 1 32 45 PM" src="https://user-images.githubusercontent.com/50714166/148270006-3798f0f2-5b2a-4560-8ebc-99b2ccfb2475.png">

change to "Gitlab Issues:

**Comment by Shoalsteed** [comment]
<img width="756" alt="Screen Shot 2022-01-05 at 1 34 12 PM" src="https://user-images.githubusercontent.com/50714166/148270215-02f0dfe8-af7a-4e6f-b584-135960017bcc.png">
some of these links do not work - are they active? 
HTTP Proxy
CONNECT Proxy
IRC Proxy
SOCKS IRC Proxy
Streamr Proxy
HTTP Bidir Proxy

**Comment by Shoalsteed** [comment]
Get Involved & Software licence page - tidy up

**Comment by Shoalsteed** [comment]
tech intro - pull apps that are not maintained

**Comment by luciewho** [comment]
Tech Docs (https://geti2p.net/en/docs)

https://geti2p.net/spec/configuration

This page is the same URL for 

- Configuration File Format (under Application Layer Topics) *keep this one possibly only
- I2P Tunnel Configuration (appears under Application Layer API and Protocols) *probably get rid of this one

Note: Page Title is Configuration File Specification. Does not match link names. *change link to Specification instead of Format
DONE

**Comment by luciewho** [comment]
Tech Docs (https://geti2p.net/en/docs)

https://geti2p.net/en/docs/how/elgamal-aes

This page is the same URL for 
- ElGamal/AES+SessionTag encryption (under End to End Encryption) *keep this page
- ElGamal/AES for Build Request Encryption (Tunnels) *removed this page

Note: Page title matches first link name, "ElGamal/AES + SessionTag Encryption"

DONE

**Comment by luciewho** [comment]
Tech Docs (https://geti2p.net/en/docs)

https://geti2p.net/spec/updates

This page is the same URL for
- Router Software Updates (under Other Router Topics) *name was changed to Software Update Specification
- Router Reseed Specification (under Network Database) *get rid of this page

Note: Page title is "Software Update Specification." Does not match link names.

*idk will research

DONE

**Comment by luciewho** [comment]
Tech Docs (https://geti2p.net/en/docs)

https://geti2p.net/spec/cryptography

This page is the same URL for (note: anchor links for 4 of them)

- ElGamal and AES Cryptography Details (under End-to-End Encryption) https://geti2p.net/spec/cryptography *keep this one. changed link name to Low Level Cryptography Specification
- ElGamal and AES Cryptography Details (under Tunnels) https://geti2p.net/spec/cryptography *removed this page
- **Cryptographic Hashes (under Network Database) https://geti2p.net/spec/cryptography#SHA256 (anchor link does not work)**
DONE except the one in bold

Note: Page title is "Low-level Cryptography Specification." Does not match link names.

**Comment by luciewho** [comment]
Tech Docs (https://geti2p.net/en/docs)

https://geti2p.net/spec/common-structures

This page is the same URL for
- Common data structures specification (under Client-to-Router Interface API and Protocol) *remove this one
- Common data structures specification (under Router Message Protocol)
*possibly turn into anchor links, different names for link 

Note: Page title is "Common structures Specification"

DONE

**Comment by luciewho** [comment]
Tech Docs (https://geti2p.net/en/docs)

https://geti2p.net/en/docs/tunnels/implementation

Page title is "Tunnel Implementation" which does not match link name 
Tunnel building and encryption (under Tunnels)

*Change link name to Tunnel Implementation - DONE

**Comment by luciewho** [comment]
Tech Docs (https://geti2p.net/en/docs)

https://geti2p.net/spec/tunnel-creation

Page title is "Tunnel Creation Specification" which does not match link name
Tunnel building specification (ElGamal) (under Tunnels)

*Change page title to Tunnel building specification (ElGamal) - DONE

**Comment by luciewho** [comment]
Tech Docs (https://geti2p.net/en/docs)

https://geti2p.net/spec/tunnel-creation-ecies

Page title is "ECIES-X25519 Tunnel Creation" which does not match link name
Tunnel building specification (ECIES-X25519) (under Tunnels)

*Change the page title to Tunnel building specification (ECIES-X25519) - DONE

**Comment by luciewho** [comment]
Tech Docs

https://geti2p.net/spec

Page title is "I2P Specification Documents", the link name is "Specifications". Is there a better title to go with for consistency?

*change link name to I2P Specification Documents - DONE

**Comment by eyedeekay** [comment]
> Tech Docs (https://geti2p.net/en/docs)
> 
> https://geti2p.net/en/docs/how/elgamal-aes
> 
> This page is the same URL for
> 
>     * ElGamal/AES+SessionTag encryption (under End to End Encryption)
> 
>     * ElGamal/AES for build request encryption (under Tunnels)
> 
> 
> Note: Page title matches first link name, "ElGamal/AES + SessionTag Encryption"

I need to research this
