### ISSUE TITLE
Post Install Work

### ISSUE THREAD

**Issue by Shoalsteed** [Shoalsteed/UX#6]
https://geti2p.net/en/download/0.9.49/clearnet/https/download.i2p2.de/i2pinstall_0.9.49.jar/download

Post-install work
After running the installer on windows, simply click on the "Start I2P" button which will bring up the router console, which has further instructions.

**_BUT I AM INSTALLING ON A MAC_**

On Unix-like systems, I2P can be started as a service using the "i2prouter" script, located in the directory you selected for I2P. Changing to that directory in a console and issuing "sh i2prouter status" should tell you the router's status. The arguments "start", "stop" and "restart" control the service. The router console can be accessed at its usual location. For users on OpenSolaris and other systems for which the wrapper (i2psvc) is not supported, start the router with "sh runplain.sh" instead.

**_BE SPECIFIC. " ON OSX START I2P LIKE THIS, AND SO ON. DO NOT ASSUME EVERY USER KNOWS WHAT A UNIX LIKE SYSTEM IS_**

When installing for the first time, please remember to adjust your NAT/firewall if you can, bearing in mind the Internet-facing ports I2P uses, described here among other ports. If you have successfully opened your port to inbound TCP, also enable inbound TCP on the configuration page.

_**BE SPECIFIC HERE. IF THIS DOES NOT HURT PERFORMANCE, MAKE IT A SUGGESTION. AND LETS CONSIDER THAT IF WE ARE MAKING SOFTWARE FOR EVERYONE NOT EVERYONE IS GOING TO WANT TO DO THIS OR UNDERSTAND THIS.**_

Also, please review and adjust the bandwidth settings on the configuration page, as the default settings of 96 KBps down / 40 KBps up are fairly slow.

**_HONESTLY, I FEEL LIKE AT THIS POINT WE ARE ASKING TOO MUCH OF USERS._** 
**_Consider too that the install process is upwards of 30 steps. I might feel like throwing up my hands and walking away._** 

If you want to reach I2P Sites via your browser, have a look on the browser proxy setup page for an easy howto.

**_CHANGE THIS TOO A SOLUTION THAT IS PHRASED : START BROWSING THE I2P NETWORK THIS WAY_**

Your web browser will need to be configured in order to browse web sites on I2P and to utilize the outproxies available within I2P. Below are walkthroughs for some of the most popular browsers.

**Comment by Shoalsteed** [comment]
<img width="399" alt="Screen Shot 2021-03-23 at 8 33 17 AM" src="https://user-images.githubusercontent.com/50714166/112146875-76e39d00-8bb2-11eb-9129-f9e282e6d617.png">

<img width="243" alt="Screen Shot 2021-03-23 at 8 35 56 AM" src="https://user-images.githubusercontent.com/50714166/112147229-d5108000-8bb2-11eb-8e2a-6befea410868.png">

this does not match the Post install instruction and gives the impression of a never ending download.

"Post Install Work" = I2P Router Getting Started Configuration

**Comment by Shoalsteed** [comment]
<img width="224" alt="Screen Shot 2021-03-23 at 8 34 45 AM" src="https://user-images.githubusercontent.com/50714166/112147062-a85c6880-8bb2-11eb-8d7b-e2a58d5768da.png">

can this be put on the actual download page?

**Comment by Shoalsteed** [comment]
also - is there any merit to adding an "oops, I forgot to add Java, get it here" prompt? 
- how about a link to troubleshooting and FAQ?

**Comment by Shoalsteed** [comment]
Having had to set up a browser just to use the regular internet, I feel like right now we do not ask too much of users, but that we do ask too much with our language. It is a bit of a walled garden. 

Workflow:
Download 
Starting Download triggers this page
what should a person see next? 
I do not think a bunch of info about the router or NATS or Bandwidth
I want to see support for what is actually happening: download
So maybe move install guides here?
Have clearly labeled section for configuring the ability to browse the I2P network.

**Comment by Shoalsteed** [comment]
or, get rid of this page entirely and make our download page similar to Mullvad
https://mullvad.net/en/
<img width="413" alt="Screen Shot 2021-03-23 at 9 15 53 AM" src="https://user-images.githubusercontent.com/50714166/112152367-9a114b00-8bb8-11eb-96d5-1c764340f084.png">

**Comment by Shoalsteed** [comment]
<img width="619" alt="Screen Shot 2021-03-23 at 9 31 18 AM" src="https://user-images.githubusercontent.com/50714166/112154323-8a930180-8bba-11eb-88b3-ace874ba73a5.png">

Here we should clarify outproxy simply : I2P does not connect you to the Internet, for that you will require an outproxy, which is made available in the router console. We also suggest that if accessing sites and services on the Internet is something you need to do regularly and with discretion , you may wish to use Tor for that specific use case"

**Comment by Shoalsteed** [comment]
<img width="616" alt="Screen Shot 2021-03-23 at 9 36 37 AM" src="https://user-images.githubusercontent.com/50714166/112155040-4bb17b80-8bbb-11eb-918f-259e44317c15.png">

what is a more simple way to say this?

**Comment by HN-ux** [comment]
> 
> 
> Having had to set up a browser just to use the regular internet, I feel like right now we do not ask too much of users, but that we do ask too much with our language. It is a bit of a walled garden.
> 
> Workflow:
> Download
> Starting Download triggers this page
> what should a person see next?

>>>>"After installing I2P and java, here are further considerations"
**browser configuration**
recommendations for users **Firefox(link to page), Chrome(link to page), Internet Explorer(link to page) etc** 

> I do not think a bunch of info about the router or NATS or Bandwidth

>>>bandwidth info already features in the set up wizard


> I want to see support for what is actually happening: download
> So maybe move install guides here?
> Have clearly labeled section for configuring the ability to browse the I2P network.

**Comment by HN-ux** [comment]
> 
> 
> also - is there any merit to adding an "oops, I forgot to add Java, get it here" prompt?
> 
>     * how about a link to troubleshooting and FAQ?
>>>>yes! related to the install/download process

**Comment by HN-ux** [comment]
> 
> 
> <img alt="Screen Shot 2021-03-23 at 8 33 17 AM" width="399" src="https://user-images.githubusercontent.com/50714166/112146875-76e39d00-8bb2-11eb-9129-f9e282e6d617.png">
> 
> <img alt="Screen Shot 2021-03-23 at 8 35 56 AM" width="243" src="https://user-images.githubusercontent.com/50714166/112147229-d5108000-8bb2-11eb-8e2a-6befea410868.png">
> 
> this does not match the Post install instruction and gives the impression of a never ending download.

![image](https://user-images.githubusercontent.com/80400452/112675931-b2ef5a00-8e5f-11eb-9b90-ecfa88defb2c.png)
plus  usually the word "downloading" would be animated somehow. Maybe the last 3 dots would be moving

> "Post Install Work" = I2P Router Getting Started Configuration

**Comment by HN-ux** [comment]
I have a little trouble reading the information on some screenshots

![image](https://user-images.githubusercontent.com/80400452/112676505-6c4e2f80-8e60-11eb-8e1b-6565b255f531.png)

**Comment by HN-ux** [comment]
![s](https://user-images.githubusercontent.com/80400452/112677785-1084a600-8e62-11eb-9887-a9e721f1b590.png)

**Comment by HN-ux** [comment]
![image](https://user-images.githubusercontent.com/80400452/112678483-e2ec2c80-8e62-11eb-838f-38042db87736.png

**Comment by Shoalsteed** [comment]
- Maybe show set up wizard steps
- put NAT / Firewall here as a suggestion as a way to support the network the same way we talk about bandwidth.
- remove bandwidth suggestion, we have good defaults in place in the set up wizard
- Start browsing the I2P network! Best ways to do that / links
- outproxy: We suggest that if accessing sites and services on the Internet is something you need to do regularly and with discretion , you may wish to use Tor for that specific use case"

**Comment by Shoalsteed** [comment]
<img width="499" alt="Screen Shot 2021-04-20 at 8 53 25 AM" src="https://user-images.githubusercontent.com/50714166/115399157-e77fd880-a1b5-11eb-85b3-c19a29846740.png">

**Comment by HN-ux** [comment]
User engagement
OS win 10

Post download page comments:
•	Good info the screenshots help a lot
•	Is there a reason for the last bit to be in italics?

**Comment by Shoalsteed** [comment]
This has been moved to another issue and updates have been worked into new wireframes waiting for implementation.
