### ISSUE TITLE
Android app: Unfortunate bandwidth setting options

### ISSUE THREAD

**Issue by marek22k** [Shoalsteed/UX#64]
A kind of scrollbar is used in the Android I2P app to set the bandwidth. This is very, very difficult to set to a specific value (e.g. 512KB/s). Personally, I would recommend some kind of text box or input box.
![153638451-33f9dbe5-afca-41de-a256-c7cadf6c55a3](https://user-images.githubusercontent.com/46723399/153663289-17d5a4b0-7a29-4b7b-95d4-6620d6654fb2.png)

Furthermore, you cannot specify values over 1000 KB/s. This may be sufficient for older models, but without 5G I sometimes achieve 5 MB/s in the download. This problem would also be solved if you switched to the text box, since you can set any value there.

**Comment by Shoalsteed** [comment]
would a drop down with pre-populated options be a better option?

**Comment by marek22k** [comment]
It would also be a possibility. On the other hand, in the desktop version there is also a possibility to enter numbers directly. For example, a person could do a speed test and want to enter the values from the speed test there. If these values were not present, this would again be a problem.
Or you make a drop-down menu and somewhere an option "advanced" and then comes to a direct input.

**Comment by Shoalsteed** [comment]
I think that figuring out a simple metric that does the work ( gives the options) with custom option could work.

**Comment by marek22k** [comment]
Do you have an example how that could look like? I know very little about Android development, so I don't know what the elements look like there.

**Comment by eyedeekay** [comment]
This probably amounts to the replacement of a UI element only to implement. Remind me right after the release and I'll take a look at it, if it's as easy as I think we can can get it done early in the 1.8.0 cycle.

**Comment by Shoalsteed** [comment]
Resolved/ then cause issues.
