### ISSUE TITLE
Android app: Different languages in the app

### ISSUE THREAD

**Issue by marek22k** [Shoalsteed/UX#65]
The Android app does not stick to the language selected in the setup. I selected English, but somethings is displayed in German, my phone language. Parts of the app are in English and parts in German. In Germany, a mix of German (Deutsch) and English (Englisch) is called Denglisch.

![153638991-d120f6ac-ac4b-452f-9e68-94d08f5dce9e](https://user-images.githubusercontent.com/46723399/153663211-14dbfa64-a9cf-4335-ba0b-4e579cf5ba42.png)

**Comment by Shoalsteed** [comment]
How are the translations managed for Android ie are they pulled from  transfex? Is this in part due to incomplete translations or a code issue?

**Comment by marek22k** [comment]
Well, incomplete translations would mean that not everything has English translations, which I doubt. I would guess that in some places it checks for the phone language and in some places for the language set in the app.

**Comment by eyedeekay** [comment]
This one, on the other hand, fills me with dread. If our language settings aren't being applied across the whole application finding out why is going to be something obscure. Thanks for the report, this one is going to be on my list for 1.8.0

**Comment by Shoalsteed** [comment]
completed
