### ISSUE TITLE
Matrix Bot

### ISSUE THREAD

**Issue by Shoalsteed** [Shoalsteed/UX#69]
Is there a way to make the page that the link leads to  look different? Like, making it look like the official I2P matrix / discord ?

**Comment by marek22k** [comment]
Unfortunately not as far as I know. However, I read that the site looked even worse a few versions ago. The actual invitation system in Matrix for private rooms / spaces is that you invite users individually and do not distribute a link.

**Comment by Shoalsteed** [comment]
okay , thanks for that. We will make any changes that we can when we can.
