### ISSUE TITLE
Gray font on blue background

### ISSUE THREAD

**Issue by marek22k** [Shoalsteed/UX#77]
On mobile devices, the bottom of the page (geti2p.net) with the various links is shown in gray text on a blue background. It is extremely difficult to read
![Screen Shot 2022-03-06 at 14 35 25](https://user-images.githubusercontent.com/46723399/156927924-8ae283d9-4523-4b88-8ced-f063eedb431b.png)

**Comment by Shoalsteed** [comment]
good catch! Thanks @marek22k
