### ISSUE TITLE
Make an I2P Site/ Torrent

### ISSUE THREAD

**Issue by Shoalsteed** [Shoalsteed/UX#8]

**Comment by HN-ux** [comment]
Start....
In router console, press "web server"

![image](https://user-images.githubusercontent.com/80400452/112531920-16b24e00-8da0-11eb-8821-7a510d7cf366.png)

Pick file corresponding to user OS

![image](https://user-images.githubusercontent.com/80400452/112532238-7dd00280-8da0-11eb-8aa2-209ae583db4f.png)

**Comment by Shoalsteed** [comment]
Mac instructions need to direct people to :
Finder
applications
I2P Folder
Open Folder
eepsite
docroot
help
template

**Comment by Shoalsteed** [comment]
This still needs to be resolved.
