### ISSUE TITLE
Download Page 

### ISSUE THREAD

**Issue by Shoalsteed** [Shoalsteed/UX#9]
![1](https://user-images.githubusercontent.com/50714166/112362101-762e3200-8caa-11eb-9dcd-5f93589886ce.png)
![2](https://user-images.githubusercontent.com/50714166/112362114-79c1b900-8caa-11eb-87f6-e11ed61d8138.png)
![3](https://user-images.githubusercontent.com/50714166/112362125-7d554000-8caa-11eb-8ade-c2268573f1a6.png)
![4](https://user-images.githubusercontent.com/50714166/112362149-80503080-8caa-11eb-953e-013ef03d4b40.png)

**Comment by Shoalsteed** [comment]
maybe get rid of the windows icon

**Comment by Shoalsteed** [comment]
would install guides be better on the post download page?

**Comment by HN-ux** [comment]
> 
> 
> ![1](https://user-images.githubusercontent.com/50714166/112362101-762e3200-8caa-11eb-9dcd-5f93589886ce.png)
> ![2](https://user-images.githubusercontent.com/50714166/112362114-79c1b900-8caa-11eb-87f6-e11ed61d8138.png)
> ![3](https://user-images.githubusercontent.com/50714166/112362125-7d554000-8caa-11eb-8ade-c2268573f1a6.png)
> ![4](https://user-images.githubusercontent.com/50714166/112362149-80503080-8caa-11eb-953e-013ef03d4b40.png)



> 
> 
> would install guides be better on the post download page?
maybe not

**Comment by HN-ux** [comment]
![update](https://user-images.githubusercontent.com/80400452/112536061-e9b46a00-8da4-11eb-88b3-ff86de7990f0.png)

**Comment by HN-ux** [comment]
![win dep](https://user-images.githubusercontent.com/80400452/112537902-25503380-8da7-11eb-917b-32cb8a21bc6d.png)

**Comment by HN-ux** [comment]
Attach guides for each user OS

 ![i](https://user-images.githubusercontent.com/80400452/112539469-f2a73a80-8da8-11eb-84dc-50fdd2bb050c.png)

**Comment by HN-ux** [comment]
This button doesn't do anything when i click on it. Maybe leave out?

![d](https://user-images.githubusercontent.com/80400452/112540594-46665380-8daa-11eb-8746-0e44daf48fb5.png)

**Comment by HN-ux** [comment]
for 
![image](https://user-images.githubusercontent.com/80400452/112541087-e0c69700-8daa-11eb-9a2a-a4d90b0ee1d4.png)

include a screenshot showing the router console(applications)

![image](https://user-images.githubusercontent.com/80400452/112541250-153a5300-8dab-11eb-8b62-2e99199bc6e4.png)

**Comment by Shoalsteed** [comment]
![Add a little bit of body text (1)](https://user-images.githubusercontent.com/50714166/112651579-e9f34a80-8e22-11eb-86f5-28e8959c0e02.png)

**Comment by Shoalsteed** [comment]
<img width="560" alt="Screen Shot 2021-03-24 at 1 52 18 PM" src="https://user-images.githubusercontent.com/50714166/112652003-53735900-8e23-11eb-9626-a2b6587862ad.png">

_**"For support with installing I2P and connecting to the network, please see the I2P Install Guide."**_

This removes "dependencies" with the action , or tried to. If we need to install Java and set up a browser, these are things that are needed to "install and connect" - which is a more clear way to describe the action.

_It is ironic that the word dependency in this case relies on its own dependency of what someone needs to be familiar with when the  the word is used in this context ....._

**Comment by Shoalsteed** [comment]
![simplified Download](https://user-images.githubusercontent.com/50714166/113761698-c0b9a080-96e5-11eb-9d96-f78d405cee48.png)

**move OS instruction for headless installs to Install guides

**Comment by Shoalsteed** [comment]
![downloadpagebanner](https://user-images.githubusercontent.com/50714166/114731882-1575a080-9d10-11eb-8c1b-e3cb1607d8cf.png)

Getting Started

The I2P software includes everything you need to connect to the I2P network. A set up wizard will help you configure a few important things like how much bandwidth you would like to share while your router begins to make connections to the network. After the set up wizard is complete, you will be directed to the console home page where you can access the rest of the applications or configure, monitor, or troubleshoot your I2P connections.

For most platforms and systems, setting I2P installed and running will consist of up to three steps.

	•	_Install Java_: I2P is written in Java and requires a Java system to be installed to run. In addition to the I2P download, you need to install Java if you do not have it already installed. I2P requires Java Runtime Version 7 or higher. (Oracle, OpenJDK, or IcedTea Java Version 7 or 8 recommended, except Raspberry Pi: OpenJDK 9 for ARM, PowerPC: IBM Java SE 7 or 8)  Determine your installed Java version here or type java -version at your command prompt.

 Only two platforms do not require Java to be installed before I2P is installed, those platforms are:
	◦	_Android_: Android comes with a Java virtual machine as part of the platform, which I2P for Android uses. Therefore it is not necessary to install Java to use I2P for Android.
	◦	_Debian and Ubuntu_: On Debian and Ubuntu when using a .deb package to install, the system will automatically install and configure a Java environment for you.
	•	Install I2P: Once you have Java installed, you should run the I2P installer for your platform. This step applies to all systems.
	•	_Install/Configure a Browser_(Optional): Finally, you'll need to configure applications to use I2P. Many applications can use I2P, but the first application most people configure is a Web Browser for browsing I2P sites. Detailed instructions are available on the Browser Page.
_Windows: Java 8 is recommended. Java 9 or higher may not work._ 

Release Notes
	•	Release Notes 
	•	Change Log 
	•	Debian Change Log 
	•	Android Change Log 
	•

**Comment by HN-ux** [comment]
User feedback on https://geti2p.net/en/download

OS win 10 (All users) 

•	    Can the explanation can be done using less words?
•           It is comprehensive enough (for people who love reading (lool)
•           It is clear for me. I can easily access it by choosing my OS on the top left corner
•           Ya there's a lot of information
•           For this one, I assume the users will be people with some knowledge so they will understand exactly what they are doing. If you are new to the whole concept, it might be a struggle

**Comment by Shoalsteed** [comment]
What is clear to me is the issue that is caused by trying to be very transparent / use what are technical workflows to indicate trust can lead to making people feel confused or hesitant.
There needs to be a compromise of enough words and the right words and assessing what is Product info and what is project info in every step.

**Comment by Shoalsteed** [comment]
wireframes completed and waiting on implementation.
